- .github/workflows/main.yaml
> chore: download artifact action added to pipeline

- packages/docs/src/pages/_app.tsx
**TASK**: 
Closes #29 
Currently, the cursor position is not aligning with the line and position after the character where it should be.
To fix that simple solution is to decrease the extra padding it is getting.
**Steps to Compare**
- Go to any page where a live editor is available. (Suppose https://nextui.org/docs/components/checkbox)
- Click on the live editor window
|Current | This PR|
|-----------|-----------|
|![Screenshot from 2021-09-17 15-24-36](https://user-images.githubusercontent.com/43095489/133759933-14ed3530-8449-4da7-9a2a-eb4250cd93a1.png)|![Screenshot from 2021-09-17 15-27-23](https://user-images.githubusercontent.com/43095489/133760350-b99629fc-15d9-4f0d-8a70-69a3318f7300.png)|
|            |             |
|----------|-----------|
|**Current** …
> fix: Wrong cursor position in the live editor

- .vscode/settings.json
**TASK**:  Closes #35 
When I open any component, the eslint doesn't load the current workspace configuration and gives an error because it can't find the tsconfig.
> fix: eslint extension with workspaces

- packages/nextui/src/tooltip/__test__/index.test.tsx
- packages/nextui/src/tooltip/tooltip-content.tsx
- packages/nextui/src/tooltip/tooltip.tsx
https://github.com/nextui-org/nextui/issues/32
I don't add ARIA tags but improve the accessibility of the tooltip for persons that don't have a mouse or need that the tooltip be treat as that by screenreaders
> fix(tooltip): a11y

- packages/nextui/src/loading/__tests__/__snapshots__/index.test.tsx.snap
- packages/nextui/src/loading/__tests__/index.test.tsx
- packages/nextui/src/loading/loading.tsx
- packages/nextui/src/loading/spinner.tsx
#32
In default cases the loading frames doesn't have a way to notify blind users about what the page is doing. So, I just add a default case for that
> fix(loading): accesibility

- packages/nextui/src/input/__tests__/__snapshots__/index.test.tsx.snap
- packages/nextui/src/input/__tests__/__snapshots__/password.test.tsx.snap
- packages/nextui/src/switch/__tests__/__snapshots__/index.test.tsx.snap
- packages/nextui/src/switch/__tests__/index.test.tsx
- packages/nextui/src/switch/switch.tsx
**TASK**: https://github.com/nextui-org/nextui/issues/40
Add [accessibility properties](https://www.w3.org/TR/wai-aria-1.1/#switch) to `Switch`  component and tests to ensure the new behaviour.
> Chore switch accessibility

- packages/docs/content/docs/components/link.mdx
**TASK**: 
I was going through the docs, saw a spelling mistake
> Fix Spelling "navigate" in docs

- package.json
- packages/docs/package.json
- packages/docs/src/layouts/header.tsx
- packages/docs/src/pages/_document.tsx
- yarn.lock
> Fix 57/cumulative layout shift

- packages/docs/content/docs/components/input.mdx
- packages/docs/src/components/playground/dynamic-live.tsx
- packages/docs/src/utils/index.ts
Input email validation was wrong in the docs section Helper Text, for solving it the validation function was moved to utils file and globally imported into the dynamic live code
> fix: validation function moved to utils file

- packages/docs/content/docs/components/input.mdx
`color` prop added to input sun content example
> fix: sun input does not have the color prop

- packages/nextui/src/index.ts
- packages/nextui/src/input/index.ts
- packages/nextui/src/input/input.tsx
Closing:
#113 
Focus styles removed
> fix(input): focus styles removed

- packages/nextui/src/card/card.tsx
Closing:
#117 
`cardConfig` useMemo wasn't listeing to the background and cover prop changes
> fix(card): bgColor added as dependency to config useMemo

- packages/nextui/src/card/card.tsx
Closing :
#121 
Do not preventDefault keyboard event in the card to let the input fields listen
> fix(card): Do not preventDefault keyboard event in Card

- .github/workflows/main.yaml
- .gitignore
- CONTRIBUTING.MD
- apps/docs/.eslintrc.json
- apps/docs/src/lib/docs/config.ts
- packages/react/README.md
- scripts/update-index-docs.ts
> fix: docs path

- apps/docs/content/docs/theme/dark-mode.mdx
> ✏️ Fixed typo (usign -> using)

- apps/docs/content/docs/guide/getting-started.mdx
> fix: community typo

- packages/react/src/input/input.tsx
#143 
- clear button type forced to type button in order to avoid clear input on submit
> fix(button): clear button type forced to type button

- packages/react/src/checkbox/checkbox.tsx
Default space removed from checkbox
> refactor(checkbox): remove default space

- packages/react/package.json
#134 
- @babel/runtime added as a dependency
> fix(nextui): @babel/runtime added as a dependency

- apps/docs/src/layouts/docs.tsx
**TASK**:  #170 
More space was added to the sidebars in order to avoid losing information
> fix(docs): space added to the sidebars

- apps/docs/src/components/hero/index.tsx
- apps/docs/src/components/home/custom-themes.tsx
- apps/docs/src/components/home/dark-mode.tsx
- apps/docs/src/components/templates/player/player.tsx
- apps/docs/src/components/templates/player/styles.ts
- apps/docs/src/pages/index.tsx
- packages/react/src/switch/index.ts
**TASK**:  #177 
Closes #177 
The scope of `Dark mode is effortless Switch was reduced in order to get a faster switching themes
https://user-images.githubusercontent.com/30373425/151646266-24120072-1e4b-46b4-aa81-23fa7b41a1d8.mov
> fix(docs-dark-mode): workaround applied to reduce the switching themes delay

- packages/react/README.md
**TASK**: Fixing typo in README
Correcting spelling of `Community`
> Fixing typo in README

- apps/docs/content/docs/components/link.mdx
> Fixed typo (usign -> using)

- packages/react/src/text/child.tsx
> Removed Child ClassName from Text Component

- apps/docs/src/components/community/community.tsx
Revising the typos I noticed while scrolling through the (beautiful) docs site!
> docs: revising "community" typos

- apps/docs/content/docs/components/card.mdx
**TASK**: Fixes error in css attribute on Live Documentation
<Text weight={500} style={{ opacity: 0.6 }}>    
&nbsp; |
&nbsp; |
&nbsp; |
&nbsp; v
<Text css={{ color: "$accents4", fontWeight: "$semibold" }}>
> Updated Live Code Example Documentation in Card Component

- apps/docs/content/docs/components/switch.mdx
**TASK**:  Minor changes to Switch Documentation
Removing Gradient from colour type as it's no longer in use
> Removed Gradient Type from Switch Documentation

- apps/docs/src/components/nav-link/index.tsx
- apps/docs/src/components/sidebar/category.tsx
- The sidebar NavLink component was migrated to Stitches styles and unwrapped from a `div` component
> fix: sidebar link

- apps/docs/package-lock.json
- apps/docs/src/components/theme-switch/index.tsx
- apps/docs/src/components/theme-toggle/index.tsx
**TASK**: Potential fix for https://github.com/nextui-org/nextui/pull/200
Instead of getting isDark state from next-themes, it will be better to get it from next-ui to sync up with theme. Also this might fix the pull request i put above.
> use `useTheme` from nextui instead of next-themes

- .github/workflows/main.yaml
- PR's Vercel preview configured in the pipeline
> feat(pipeline): pr added to vercel preview deploy

- apps/docs/next-env.d.ts
- apps/docs/package.json
- apps/docs/tsconfig.json
- yarn.lock
**TASK**: https://github.com/nextui-org/nextui/issues/110
Ran the following commands from the official upgrade guide here - https://nextjs.org/docs/upgrading
```shell
yarn add react@latest react-dom@latest
yarn add next@latest
```
> chore: update nextjs version

- apps/docs/content/docs/theme/customize-theme.mdx
- apps/docs/content/docs/theme/dark-mode.mdx
- apps/docs/content/docs/theme/default-theme.mdx
- apps/docs/content/docs/theme/override-styles.mdx
- apps/docs/content/docs/theme/utilities.mdx
- apps/docs/src/components/home/customization.tsx
> fix(docs): using typos

- packages/react/src/input/input.styles.ts
- packages/react/src/textarea/textarea.stories.tsx
**Closes**:  #240 
Textarea top position was being overridden by the input `top` position
> fix(textarea): top position on focused

- packages/react/package.json
- packages/react/src/input/input.stories.tsx
- packages/react/src/input/input.tsx
- packages/react/src/theme/theme-provider.tsx
- yarn.lock
- @react-aria/label included in order to provide label and input aria ids
- @react-aria/ssr included in order to guarantee the same label and input's ids both on the server and on the client
> fix(input): label and input id mismatch solved

- apps/docs/content/docs/components/avatar.mdx
> Changed grammar errors.

- packages/react/src/progress/progress.styles.ts
> Typo in object

- apps/docs/content/docs/components/input.mdx
Fixed a typo for Important note.
**TASK**:
> Fixed a typo.

- packages/react/src/tooltip/__test__/index.test.tsx
- packages/react/src/tooltip/tooltip.stories.tsx
- packages/react/src/tooltip/tooltip.tsx
**TASK**: Small fix that where tooltip is showed even when theres no content was inside it. Also added relevant story to storybook.
The code
```javascript 
<Tooltip content={''} color="primary">
<Button auto flat>
Do hover here
</Button>
</Tooltip>
```
Before the change 
After the change
> fix(tooltip): Show no content if content is empty

- apps/docs/src/components/playground/dynamic-live.tsx
- apps/docs/src/components/playground/editor.tsx
**TASK**: This PR Fixes #289 
Clicking on live Editor Copy button doesn't do anything in DOC Section of website
> Fixed Copy Function in Live Editor on DOC Section of Next UI website

- packages/react/src/use-pagination/index.ts
**TASK**: Fix #324 
it seems that the `page` prop is only used in a `useState` in the old version, which means the change of this prop will merely affect the render of the `Pagination` at the first time.
> Make `Pagination` properly controlled.

- apps/docs/content/docs/components/avatar.mdx
**TASK**: `null`
I know, it's the funniest PR ever, but I did it 😅
> fix: add a missing heading in `avatar.mdx`

- packages/storybook/.storybook/main.js
- packages/storybook/.storybook/manager.js
- packages/storybook/.storybook/preview.js
- packages/storybook/package.json
I add theme toggle in storybook,it will help nextUI to develop or fix issue.
Developer can switch theme to test component between dark and light.It is amazing!
> Theme toggle of storybook

- apps/docs/package.json
- package.json
- packages/react/package.json
- yarn.lock
**TASK**: This PR is aim towards fixing issue with Next UI Components Showing Length as required library
Issue :-
> Downgrading TypeScript Version to Prevent Required Length Issue

- apps/docs/content/docs/theme/customize-theme.mdx
The `type` field is required in the latest version of `createTheme`. Also, this code snippet is missing a comma and is invalid JavaScript.
> docs: `type` is required and fix invalid JavaScript

- apps/docs/content/components/avatar/icon.ts
- apps/docs/content/components/container/autoLayout.ts
- apps/docs/content/components/container/breakpoint.ts
- apps/docs/content/components/container/default.ts
- apps/docs/content/components/container/fluid.ts
- apps/docs/content/components/container/index.ts
- apps/docs/content/components/grid/autoWidth.ts
- apps/docs/content/components/grid/default.ts
- apps/docs/content/components/grid/fluid.ts
- apps/docs/content/components/grid/hideElement.ts
- apps/docs/content/components/grid/index.ts
- apps/docs/content/components/grid/responsive.ts
- apps/docs/content/components/index.ts
- apps/docs/content/components/spacer/horizontal.ts
- apps/docs/content/components/spacer/index.ts
- apps/docs/content/components/spacer/vertical.ts
- apps/docs/content/docs/layout/container.mdx
- apps/docs/content/docs/layout/grid.mdx
- apps/docs/content/docs/layout/spacer.mdx
**TASK**: Layout Documentation Migrated to New Docs
Every Dependency has been migrated to it's own Package to Avoid Issue when switching to Codesandbox Editor
> Layout documentation updated

- apps/docs/content/docs/guide/getting-started.mdx
> Fix the link

- packages/react/package.json
- yarn.lock
> fix[react](root): @react-aria/ssr package version changed to 3.1.2

- apps/docs/content/components/input/password.ts
- apps/docs/src/styles/globalStyles.ts
**TASK**: This PR Closes #364
Added Missing Icons for Input Password Documentation
> Added Missing Input Documentation

- packages/react/package.json
- yarn.lock
**TASK**: 
This PR upgrades `@stitches/react` from 1.2.6 to 1.2.7 ([change-log](https://github.com/modulz/stitches/compare/v1.2.6...v1.2.7))
> Upgrade @stitches/react to 1.2.7

- packages/react/src/theme/types.ts
Missing keys were added to the ConfigType.Theme interface
> fix[react](theme): ConfigType.Theme interface fixed

- packages/react/src/progress/progress.styles.ts
**TASK**: 
Progress component default color variant
> fix[react](progress): color default variant

- packages/react/src/index.ts
`Drip` and `useDrip` are now being exported
> chore[react](root): drip exported

- apps/docs/content/docs/components/button.mdx
- packages/react/src/input/input.tsx
**TASK**: 
Re-uploading Input "required" parameter fix.
> Input {required} parameter fix (again)

- apps/docs/content/docs/guide/getting-started.mdx
> fix:Update getting-started.mdx

- apps/docs/src/components/home/custom-themes.tsx
> Remove dynamic import

- apps/docs/src/components/palette/index.tsx
- apps/docs/src/components/palette/item.tsx
- packages/react/src/table/table.styles.ts
- `overflow: auto` applied in order to avoid diplaying scrollbars when not needed
- padding right added to table cells
> Fix 406/table overflow

- packages/react/src/grid/grid-container.tsx
> Container typo

- packages/react/src/button/button.styles.ts
- packages/react/src/button/button.tsx
Closes # 
Ghost button on "Hover" / "Focused" states on mobile fixed
> fix: ghost button fixed on mobile

- apps/docs/content/docs/theme/customize-theme.mdx
Fix comma typo in [customize theme code example](https://nextui.org/docs/theme/customize-theme#theme-type)
```diff
- type: 'dark'
+ type: 'dark',
```
No
> fix(docs): comma typo in customize theme code example

- apps/docs/src/styles/globalStyles.ts
Closes #281
This was the problem mentioned in #281.
> fix: horizontal overflow

- apps/docs/content/docs/guide/getting-started.mdx
- apps/docs/content/docs/guide/nextui-plus-nextjs.mdx
Fix missing key at getting started and NextUI + Next.js pages
Add React.Children.toArray()
No
> fix(docs): missing key in code examples

- apps/docs/content/docs/theme/default-theme.mdx
Updated Spelling & Grammar mistakes in the NEXTUI Default Theme Page
minor text update
minor text update
no
this is my first contribution on GitHub :)
> Docs - Updated Spelling & Grammar - Default Theme Page

- apps/docs/content/landing/index.tsx
> docs: fix typos

- apps/docs/content/docs/guide/getting-started.mdx
Closes #574
Add react import code to document
No
> docs: fix import error

- apps/docs/content/components/card/variants.ts
The [second code example](https://nextui.org/docs/components/card#variants) in `Card` component doc can't be compiled in CodeSandbox due to unimported components, which may lead to confusion.
Unimported components lead to errors in CodeSandbox.
The code runs.
> fix(docs): unimported component in Card example

- apps/docs/content/components/tooltip/trigger.ts
- packages/react/src/tooltip/tooltip.stories.tsx
Closes #527
The trigger section of tooltip storybook and [the same part of doc](https://nextui.org/docs/components/tooltip#trigger) did not respond to click event.
Tooltip did not respond to click event because of the conflict with button.
Change button to card to reduce the confusion and test the function correctly in storybook.
> fix(react-tooltip): tooltip story

- apps/docs/content/docs/components/image.mdx
> docs: wrong case in image props

- apps/docs/src/components/index.ts
- apps/docs/src/components/kbar-wrapper/index.tsx
- apps/docs/src/lib/kbar-actions.ts
- apps/docs/src/pages/_app.tsx
Closes [#598](https://github.com/nextui-org/nextui/issues/598)
Kbar was using a function `changeTheme` that was not related to `next-themes`. This was create a misalignment in some part of the docs app.
My approach was to make Kbar Change Theme functionality use `next-themes` hook to change theme.
Some styles work not being correctly applied on theme change.
Theme is applied correctly.
No
> fix(docs): Kbar change theme

- apps/docs/content/docs/theme/media.mdx
Original media page title was "Utilities".
Rename media page title as "Media"
> fix(docs): change media page title

- apps/docs/content/docs/components/loading.mdx
The property color should be changed to color property.
Closes # 
> docs: fix grammar in loading docs

- packages/react/README.md
Usually, other codebases follow this pattern, so I am suggesting these changes. 
Feel free to close if you think it's not something you want. 
Personally, I was going down by habit and I had to scroll back a few times, so I thought maybe this could help.
> Improvement: Adding links in contribution and code of conduct

- apps/docs/content/docs/components/image.mdx
> Fixed some misspellings and corrected a few types.
> No
> Fix typos in image docs

- .github/workflows/main.yaml
- Force build
- Cache with `yarn.lock` instead of `package-lock.json`
- Upgrade actions
- ubuntu 20.04
- checkout v3
- node 16
- cache v3
No
> chore(repo): Force build and upgrade some versions of action

- .github/workflows/main.yaml
- vercel.json
- Remove deploy workflow
- Update `vercel.json` config
No
> chore(repo): build and deploy with vercel

- apps/docs/content/components/input/content.ts
Closes https://github.com/nextui-org/nextui/issues/647
Fix CodeSandbox error in content `Input`.
- Export `SendIcon`.
No
> fix(docs): codesandbox error in content input

- apps/docs/content/components/radio/controlled-vs-uncontrolled.ts
A component that gets a state and the corresponding change handler as a prop, is a controlled component. (Before this commit it was the other way around in the documentation for the Radio.Group component.)
No
> DOC: fix controlled / uncontrolled in Radio

- apps/docs/content/docs/guide/getting-started.mdx
> Separate installation shell script code block for better copy-paste to terminal
From
To
No
> chore(docs): separate installation shell script code block for better copy

- apps/docs/src/components/mobile-navigation/index.tsx
- apps/docs/src/theme/shared.ts
Closes #635 
Not enough contrast on mobile sidebar
Mobile sidebar contrast improved
> fix(docs-sidebar): contrast blur

- apps/docs/src/components/notify-banner/styles.ts
- apps/docs/src/layouts/docs.tsx
- apps/docs/src/layouts/navbar.tsx
- apps/docs/src/layouts/styles.ts
- apps/docs/src/styles/globalStyles.ts
Closes #640 
The docs website scrolls up when writing characters to the documentations search bar
The docs website is no longer scrolling up when writing characters to the documentations search bar
> fix(docs-navbar): navbar position changed from sticky to fixed

- packages/react/src/table/table.tsx
Closes #772 
Striped variant fixed
#772 
Table props are now being passed to the table
> fix(react-table): props weren't being passed to the table

- apps/docs/content/components/card/default.ts
fix(docs-card): add missing import for code example.
[Code example of Card](https://nextui.org/docs/components/card#default) does not work.
[Code example of Card](https://nextui.org/docs/components/card#default) works now.
No.
Thanks for the beautiful UI library you've made!
> fix(docs-card): add missing import for code example

- packages/react/src/use-pagination/__tests__/use-pagination.test.tsx
This is a long-term branch. All PRs from this branch intend to increase UT coverage and optimize nextui source code. I will continuously commit test code to this branch.
All commits in this branch are atomic, feel free to merge PR at any time. @jrgarciadev
No
- use-pagination: statements 100% ⬆️ , branches 100% ⬆️
> unit test coverage udpate

- packages/react/src/pagination/pagination.tsx
- packages/react/src/table/table-body.tsx
- packages/react/src/table/table.stories.tsx
- packages/react/src/use-pagination/index.ts
Closes https://github.com/nextui-org/nextui/issues/798
- Increase placeholder units from `$space$14` to `$space$15`.
- Add dependency to `setPage` to be updated if necessary.
No
For the improvement of https://github.com/nextui-org/nextui/pull/839.
> fix(react-table): layout shifting and table pagination

- apps/docs/content/docs/layout/spacer.mdx
Fix the `Spacer` heading in the docs.
No
> chore(docs-spacer): heading

- apps/docs/package.json
- examples/create-next-app/package.json
- examples/create-react-app/package.json
- examples/vite-react-typescript/package.json
- examples/with-tailwindcss/package.json
- package.json
- packages/react/package.json
- packages/react/src/dropdown/dropdown-menu.tsx
- packages/storybook/package.json
- yarn.lock
> fix(build): version upgrade in all packages

- apps/docs/content/components/modal/blurBackground.ts
- apps/docs/content/components/modal/default.ts
- apps/docs/content/components/modal/fullscreen.ts
- apps/docs/content/components/modal/largeContent.ts
- apps/docs/content/components/modal/noAnimated.ts
- apps/docs/content/components/modal/preventClose.ts
- apps/docs/content/components/modal/withoutPadding.ts
- apps/docs/content/components/popover/custom-content.ts
- apps/docs/content/components/textarea/controlledUncontrolled.ts
- apps/docs/content/components/tooltip/customContent.ts
- apps/docs/content/docs/components/button.mdx
- packages/react/src/button/index.ts
Improve button-related documentation.
Add button events to the document and replace the deprecated `onClick` with `onPress`.
- Button events documentation.
- Eexport types `PressEvent, PointerType`.
No.
> feat(react-button): export types and events documentation

- packages/react/src/button/button.styles.ts
Now a focus indicatior is shown for buttons who have shadows.
https://user-images.githubusercontent.com/25524993/205450665-453631e7-bfba-44ad-bf1f-620872f19d63.mp4
> fix: added focus indicator to buttons that have a shadow

- apps/docs/content/components/radio/invalid.ts
adds a more realistic example of "invalid" checkbox use
every option is invalid
has both valid and invalid options
no
thanks for the epic library
> docs: make `invalid` radio code example more realistic

- apps/docs/content/docs/theme/default-theme.mdx
Closes # 
>changed whiten ----> within
in docs.
> correct typographical error in docs.

- apps/docs/content/docs/components/input.mdx
This PR fixes a small typo in the Input component documentation.
The change ensures that the text is grammatically correct and easier to understand for users.
> fix: typo in Input component documentation

- packages/core/theme/src/components/button.ts
rename class from text-md to text-base
Closes # 
> Fix: wrong text-md class

- apps/docs/content/docs/components/image.mdx
Just fixing a tiny typo on docs
> fixed typo on docs

- .github/ISSUE_TEMPLATE/feature_request.yml
Fixed a typo. The description of the issue stated '... improve an exiting component.'. The typo was changed to 'existing'
> There was a typo in the feature request issue template which stated `exiting` instead of `existing`.
> There is a typo in the feature request issue template description stating `exiting` instead of `existing`.
> The typo has now been edited to `existing`.
No.
NA
> Update feature_request.yml and fix typo.

- apps/docs/content/components/input/helper.ts
I edited line 63 - Excelent => Excellent
Closes # 
> refactoring helper.ts - fixed a typographical error

- apps/docs/content/components/image/showSkeleton.ts
Closes #1074 
> Image not rendering after delay.
> Image not rendering after delay.
> Image renders after delay.
No
> Fix: #1074 Updated image url

- apps/docs/content/docs/guide/nextui-plus-nextjs.mdx
> Corrected spelling of customizing

- apps/docs/src/pages/examples/navbar/disable-collapse-animation.tsx
> fix: add showIn="xs" to Navbar.Collapse #1005

- packages/react/src/use-pagination/index.ts
> fix: fix pagination page invalid

- apps/docs/content/components/image/showSkeleton.ts
- packages/react/src/image/image.stories.tsx
Closes # 
> Minimal fix in `https://nextui.org/docs/components/image#show-skeleton`
> The current API for delay isn't working (502 Bad Gateway) `http://deelay.me/`
> new API to simulate delay in showSkeleton docs `requestly.io`
> new Skeleton delay api

- packages/components/link/src/use-link.ts
> Chore(Link): Remove code redundancies

- packages/components/link/src/use-link.ts
> fix(Link): fix unknown event warning when passing onPress prop

- packages/components/modal/package.json
- packages/components/modal/stories/modal.stories.tsx
- pnpm-lock.yaml
I just noticed the missing focus and hover state.
> docs: updated story to use link component instead of basic anchor

- CONTRIBUTING.MD
I've made improvements to the grammar and formatting of the Next UI Contributing Guide. Specifically, the readability of sentences has been enhanced and the format of code blocks has been standardized.
> docs: improve contributing guide clarity

- packages/storybook/.storybook/preview.js
https://github.com/nextui-org/nextui/assets/25524993/d4d8d30b-281b-4b1c-b234-7bbc3fe6eb45
> feat: added locale select to storybook toolbar

- packages/components/modal/stories/modal.stories.tsx
> fix: fixed modal button press issue

- packages/core/theme/src/components/pagination.ts
https://github.com/nextui-org/nextui/assets/25524993/249a0029-99ac-43cc-98c2-df0749c2284e
> feat: pagination dots changes to arrows when focus visible

- packages/core/theme/src/components/navbar.ts
> fix: added min gap to navbar

- packages/components/pagination/src/pagination.tsx
- packages/components/pagination/src/use-pagination.ts
How it works now:
https://github.com/nextui-org/nextui/assets/25524993/fd67ae3b-d7eb-47e2-b8c1-1b9f35fc33c1
> fix: pagination focus is now maintained after page switching

- apps/docs/content/landing/index.tsx
Fixed a small grammatical error with the docs
Fixes grammatical error
No
> docs: Fix grammatical error

- apps/docs/app/examples/navbar/bordered/page.tsx
- apps/docs/app/examples/navbar/controlled-menu/page.tsx
- apps/docs/app/examples/navbar/custom-active-item/page.tsx
- apps/docs/app/examples/navbar/disable-menu-animation/page.tsx
- apps/docs/app/examples/navbar/disabled-blur/page.tsx
- apps/docs/app/examples/navbar/hide-on-scroll/page.tsx
- apps/docs/app/examples/navbar/static/page.tsx
- apps/docs/app/examples/navbar/usage/page.tsx
- apps/docs/app/examples/navbar/with-avatar/page.tsx
- apps/docs/app/examples/navbar/with-dropdown-menu/page.tsx
- apps/docs/app/examples/navbar/with-menu/page.tsx
- apps/docs/app/examples/navbar/with-search-input/page.tsx
- apps/docs/content/components/navbar/bordered.ts
- apps/docs/content/components/navbar/controlled-menu.ts
- apps/docs/content/components/navbar/custom-active-item.ts
- apps/docs/content/components/navbar/disable-menu-animation.ts
- apps/docs/content/components/navbar/disabled-blur.ts
- apps/docs/content/components/navbar/hide-on-scroll.ts
- apps/docs/content/components/navbar/static.ts
- apps/docs/content/components/navbar/usage.ts
- apps/docs/content/components/navbar/with-avatar.ts
- apps/docs/content/components/navbar/with-dropdown-menu.ts
- apps/docs/content/components/navbar/with-menu.ts
- apps/docs/content/components/navbar/with-search-input.ts
- packages/components/navbar/stories/navbar.stories.tsx
- fixes the structure so it is now `ul > li > a` rather than just `ul > a`
- adds `aria-current="page"`
- fixes the issue that the page jumps when you click on a link that is inside an iframe
> fix: fixed navbar link problems in docs

- packages/components/checkbox/src/checkbox-group.tsx
> fix: changed checkbox group label to be span

- packages/components/pagination/src/use-pagination-item.ts
- packages/core/theme/src/components/button.ts
- packages/core/theme/src/components/checkbox.ts
- packages/core/theme/src/components/pagination.ts
- packages/core/theme/src/components/radio.ts
- packages/core/theme/src/components/toggle.ts
- removed pressed transition from button when animations are disabled
- removed pressed transition from switch thumb when animations are disabled
- added pressed transition to checkbox, radio and pagination.
> feat: improved animations

- apps/docs/content/components/button/group-use-case.ts
> docs: improved button group-use-case example

- packages/components/input/src/textarea.tsx
> fix: added missing helper text wrapper to textarea

- apps/docs/content/blog/nextui-v2.mdx
> fix(docs): custom variants link

- apps/docs/content/docs/components/dropdown.mdx
> fix(docs): typo in dropdown.mdx

- apps/docs/app/examples/navbar/controlled-menu/page.tsx
- apps/docs/app/examples/navbar/with-avatar/page.tsx
- apps/docs/app/examples/navbar/with-search-input/page.tsx
- apps/docs/content/components/navbar/with-avatar.ts
- apps/docs/content/components/navbar/with-search-input.ts
- packages/components/navbar/stories/navbar.stories.tsx
Closes https://github.com/nextui-org/nextui/issues/1240
- `Avatar` rendered as a `button`.
- Remove `NavbarItem` to get cleaner dom.
- `NavbarContent` rendered as a `div` since its child are not list items.
No.
- Sync example and code for controlled menu section.
- Update navbar's stories.
> fix(docs): navbar examples

- apps/docs/content/components/table/use-case.ts
Closes #1236 
Use case table example fixed
> fix(table): ts use-case example, page state added

- apps/docs/components/cmdk.tsx
> fix(docs): remove autoFocus on webkit

- apps/docs/content/components/checkbox-group/custom-styles.ts
- apps/docs/content/components/radio-group/custom-styles.ts
- apps/docs/content/docs/components/radio-group.mdx
Closes # 
Fix Radio Group & Checkbox Group custom styles examples
> fix(docs): radio & checkbox custom styles

- packages/components/dropdown/src/dropdown-menu.tsx
Closes #1266 
Fix keys warning on Next.js for Dropdown component
> fix(dropdown): item keys taken out from the itemProps

- packages/core/theme/src/components/modal.ts
Closes #1263 
Modal outside scroll fixed on mobile 
> fix(modal): content placement changed on mobile when outside scroll

- packages/components/pagination/src/use-pagination.ts
> chore(use-pagination):  fix ariaLabel warning

- packages/components/pagination/src/pagination-item.tsx
> chore(pagination-item): fix react key warning

- apps/docs/content/docs/components/table.mdx
Closes https://github.com/nextui-org/nextui/issues/1318
Typo fixed.
No.
> fix(docs): typo in the loading more data section

- apps/docs/app/examples/table/use-case/page.tsx
- apps/docs/content/components/table/use-case.ts
Closes https://github.com/nextui-org/nextui/issues/1325
- Display available data count.
- Remove pagination disabled state.
- Update pagination button disabled state.
- Return to the first page when clearing the search-box.
No.
[table-use-case.webm](https://github.com/nextui-org/nextui/assets/32772271/6c521290-8692-4597-ae44-2ffdde536199)
> docs(table): use case example

- packages/components/popover/stories/popover.stories.tsx
- packages/storybook/.storybook/preview.tsx
- packages/storybook/.storybook/style.css
- added missing arg type
- removed scroll bar from all stories
- formatted styles.css using prettier
> chore: storybook improvements

- .changeset/lovely-mayflies-move.md
- packages/components/dropdown/src/dropdown-section.tsx
- packages/components/dropdown/src/use-dropdown-item.ts
Closes #1376 
Next.js key spread warning fixed
> fix(dropdown): spread key warning

- .changeset/curly-pandas-leave.md
- apps/docs/app/examples/navbar/with-search-input/page.tsx
- apps/docs/content/components/navbar/with-search-input.ts
- packages/core/theme/src/components/input.ts
Closes #1382 
- Navbar with search input example fixed
- input mainWrapper slot `h-full` class added
> fix(docs): navbar with search input example

- .changeset/stale-dolls-watch.md
- packages/utilities/react-rsc-utils/src/dom-props.ts
Closes #1388 
`slot` attr added to filter dom props function.
> fix(root): filter dom props function fixed, slot prop added

- apps/docs/content/components/card/composition.ts
Add import CardFooter at Card component composition in the tab code
> fix/add import CardFooter at Card component composition

- .changeset/clean-buses-sing.md
- packages/components/accordion/src/use-accordion.ts
- packages/components/popover/src/use-popover.ts
- packages/components/popover/stories/popover.stories.tsx
- packages/components/snippet/src/use-snippet.ts
- packages/components/user/src/use-user.ts
Closes #1409 
Add the possibility to merge the `style` prop with the one returned by `react-aria`
> fix(popover): allow passing custom z-index

- apps/docs/content/components/input/start-end-content.ts
- apps/docs/content/components/modal/form.ts
Closes #1420 
Mail filled icon import fixed in the modal  docs`Form` example
> fix(docs): modal mail icon imports

- packages/components/select/stories/select.stories.tsx
- packages/hooks/use-aria-multiselect/src/use-multiselect.ts
Quick fix for `feat/select-component`.
> fix: select aria label

- .changeset/new-phones-swim.md
- package.json
- packages/components/link/src/use-link.ts
- packages/hooks/use-aria-link/README.md
- packages/hooks/use-aria-link/package.json
- packages/hooks/use-aria-link/src/index.ts
- packages/hooks/use-aria-link/tsconfig.json
- pnpm-lock.yaml
> fix(link): warning onClick removed

- .changeset/nasty-snails-yawn.md
- packages/components/accordion/src/accordion.tsx
- packages/components/accordion/stories/accordion.stories.tsx
- pnpm-lock.yaml
> fix(accordion): hide indicator prop in accordion item

- apps/docs/content/docs/customization/dark-mode.mdx
Closes #1445
> Address the error handling in ThemeSwitcher component specified in the doc 
> Implementation of dark mode result in hydration error while following the doc
> Resolved the mentioned error while replicating the dark mode mode feature from the doc.
> updated doc handling hydration mismatch error

- .changeset/strong-trees-beam.md
- .changeset/violet-zoos-promise.md
- packages/components/dropdown/src/dropdown-menu.tsx
- packages/components/dropdown/src/use-dropdown.ts
- packages/components/popover/src/free-solo-popover.tsx
- packages/components/popover/src/popover-content.tsx
- packages/components/popover/src/use-aria-popover.ts
- packages/components/popover/src/use-popover.ts
- packages/core/theme/src/components/popover.ts
Closes #1460 
- Dropdown trigger events
- Popover arrow styles
> fix(dropdown): popover and dropdown fixes

- apps/docs/content/components/card/cover-image.ts
> fix -( Image-Tag issue in Cover-image.ts )

- apps/docs/content/components/listbox/single-selection.ts
Closes # 
> The ListboxWrapper was not being identified and because of that the component was not loading on the webpage.
> when running the code the webpage goes blank.
> It solves the issue by exporting the ListboxWrapper so that it can be identified.
> Solved error in Listbox Component

- apps/docs/components/marketing/hero/floating-components.tsx
Closes # 
Hero tooltip component levitation animation fixed
> chore(docs): hero tooltip arrow removed

- .changeset/moody-socks-yawn.md
- packages/components/snippet/src/use-snippet.ts
Closes # 
Snippet invalid props fixed
> fix(snippet): invalid props

- .changeset/khaki-spiders-joke.md
- packages/components/navbar/src/navbar-menu.tsx
> fix(navbar-menu): dismiss buttons removed to fix the scroll

- .changeset/lazy-buses-heal.md
- apps/docs/package.json
- packages/core/system-rsc/package.json
- packages/core/theme/package.json
- packages/core/theme/src/types.ts
- pnpm-lock.yaml
Closes # 
Tailwind variants upgrade
> chore(root): tailwind variants upgraded

- packages/components/pagination/src/use-pagination.ts
Reverts nextui-org/nextui#1552
> Revert "fix: fixed pagination scale animation"

- packages/components/pagination/src/use-pagination.ts
- packages/core/theme/src/components/pagination.ts
Reverts nextui-org/nextui#1222
> Revert "fix: resolved cursor issues in pagination"

- .changeset/cool-pandas-join.md
> fix(pagination): changeset

- .changeset/early-garlics-deliver.md
- packages/components/chip/stories/chip.stories.tsx
- packages/core/theme/src/components/chip.ts
> fix: set nowrap in chip

- .changeset/hip-foxes-give.md
- packages/components/card/src/card-footer.tsx
> fix(card): corrected footerStyles in card footer

- apps/docs/components/sandpack/use-sandpack.ts
- apps/docs/content/components/table/use-case.ts
- apps/docs/content/docs/components/table.mdx
- apps/docs/styles/sandpack.css
> fix(docs): table use case example fixed, sandpack tabs padding added

- CONTRIBUTING.MD
Closes # 
Update contributing note Node.js version 14 to 16.
> chore(root): update contributing.md note

- apps/docs/app/examples/table/custom-styles/page.tsx
- apps/docs/app/examples/table/use-case/page.tsx
- apps/docs/components/code-window/code-block.tsx
- packages/components/card/stories/card.stories.tsx
- packages/components/table/stories/table.stories.tsx
> fix: fix eslint warning

- apps/docs/content/components/button/custom-impl.ts
Button custom implementation example fixed
> fix(docs): button custom implement

- apps/docs/content/components/code/sizes.ts
docs: fix code Sizes demo overflow
> docs: fix code Sizes demo overflow

- apps/docs/content/components/avatar/bordered.ts
- apps/docs/content/components/avatar/colors.ts
- apps/docs/content/components/avatar/custom-fallback.ts
- apps/docs/content/components/avatar/disabled.ts
- apps/docs/content/components/avatar/radius.ts
Closes # 
Some doc page have missing ";" like below:
> docs: add missing semicolon in documentation

- .changeset/big-monkeys-notice.md
- packages/components/ripple/src/ripple.tsx
> fix(ripple): clear ripples on animation complete

- packages/components/slider/src/slider.tsx
- packages/components/slider/src/use-slider.ts
- packages/components/slider/stories/slider.stories.tsx
- packages/core/theme/src/components/slider.ts
> feat: slider steps

- .changeset/forty-vans-refuse.md
- packages/components/select/__tests__/select.test.tsx
- packages/components/select/src/select.tsx
> fix(select): add placeholder dep for renderSelectedItem

- apps/docs/content/components/select/open-state.ts
- packages/components/button/stories/button.stories.tsx
Small change to have the toggle buttons in the docs and stories follow https://www.w3.org/WAI/ARIA/apg/patterns/button
> docs: accessible toggle button in examples

- .changeset/red-hairs-thank.md
- packages/components/pagination/src/use-pagination.ts
- packages/core/theme/src/components/pagination.ts
This is just the revert of the revert.
> fix: pagination issues second try

- apps/docs/content/components/navbar/controlled-menu.ts
> fix: added missing imports in navbar

- apps/docs/content/docs/components/tabs.mdx
Closes # 
> Duplicate tabContent classNames
> Duplicate tabContent
> Delete tabContent
> Docs > Duplicate tabContent classNames

- apps/docs/content/docs/components/chip.mdx
Closes # N/A
t he => the
t he => the
t he => the
no
t he => the
> fix(docs): fix typo in chips component page

- apps/docs/content/components/select/open-state.ts
- packages/components/select/package.json
- packages/components/select/stories/select.stories.tsx
- pnpm-lock.yaml
Closes #1762
Fixes the docs and storybook issue with the controlled open stated (Select)
Select popover doesn't close when pressing the button (controlled open)
`onOpenChange` callback handled to close the Select Popover
> fix(select): add button component and update select component

- .changeset/real-moons-complain.md
- packages/components/input/src/use-input.ts
- packages/core/theme/src/components/input.ts
- packages/core/theme/src/components/select.ts
- packages/storybook/tailwind.config.js
value
The Input/Textarea/Autocomplete/Select styles were adapted to work well with custom `default` colour.
> Input/Select/Textarea/Autocomplete. styles adapted to custom default color.

- apps/docs/content/docs/guide/routing.mdx
- apps/docs/next-redirect.js
> refactor(docs): routing and add folder routes

- .changeset/angry-waves-sit.md
- packages/components/input/src/input.tsx
- packages/components/input/src/use-input.ts
- packages/components/input/stories/input.stories.tsx
- packages/components/select/src/select.tsx
- packages/components/select/src/use-select.ts
- packages/core/theme/src/components/input.ts
- packages/core/theme/src/components/select.ts
Closes # 
Fixes the Input and Select styles.
Input/Select/Autocomplete
Styles issues fixed.
> fix(input): label position and styles

- .changeset/cyan-walls-pretend.md
- packages/core/theme/src/components/input.ts
- packages/core/theme/src/components/select.ts
Closes # 
Small refactor for Input, Select, Autocomplete and Textarea font size on `sm` sizes.
> refactor(theme): update input and select component styles

- apps/docs/content/docs/components/breadcrumbs.mdx
Closes # 
Fix a typo on the breadcrumbs [page](https://nextui.org/docs/components/breadcrumbs#:~:text=the%20other%20components.-,BreadcrumItem,-%3A%20The%20component%20that).
No
> docs(breadcrumb): fix typo

- .changeset/light-snakes-develop.md
- packages/components/navbar/src/use-navbar.ts
Closes #1941 
Style prop don't pass to navbar
Style prop don't pass to navbar
Style prop added to the base navbar element.
> fix(navbar): style prop

- .changeset/beige-flies-tease.md
- packages/core/theme/src/utils/tv.ts
Closes #1933
TV function refactored to the previous version.
> fix(progress): tv function refactored

- apps/docs/content/docs/components/listbox.mdx
> docs(listbox): fix ListboxSection Props typo

- packages/components/scroll-shadow/stories/scroll-shadow.stories.tsx
> fix(scroll-shadow):  typo in scroll-shadow.stories.tsx

- apps/docs/content/docs/guide/introduction.mdx
Typos. (Actually stinking to "PRs" instead of "PR's". The grammatical format present in examples such as L's and W's is expected because it's only one letter, but does not seem to apply to multiple letters combined.
Closes # 
> Update introduction.mdx (3)

- apps/docs/components/demo-code-modal.tsx
Closes # 
> Fixed the link to components inside demo modal
> Takes to invalid path like `https://nextui.org/docs/dropdown` instead of `https://nextui.org/docs/components/dropdown`
>  corrected path
> [MINOR FIX] Fixed path in demo-code-modal.tsx

- apps/docs/content/docs/components/table.mdx
Closes # 
There was a slight typo on the table doc page.
n/a
> docs: dix typo in table docs

- apps/docs/content/docs/components/accordion.mdx
- apps/docs/content/docs/components/dropdown.mdx
> docs: typo

- apps/docs/content/components/navbar/disable-menu-animation.ts
> fix: fix missing imports in navbar

- apps/docs/content/docs/components/autocomplete.mdx
Closes # 
Fixes a typo in the autocomplete docs.
> docs(autocomplete): fix typo

- packages/storybook/.storybook/preview.tsx
Closes # 
improve storybook preview file to avoid type error
No
> chore(storybook): improve preview.tsx

- apps/docs/libs/github/api.ts
> chore: typo

- apps/docs/content/docs/guide/introduction.mdx
Fix hydration error (#2388)
Closes # 
#2388 
fix #2388 
No
> fix(docs): hydration error (#2388)

- apps/docs/content/components/tabs/form.ts
Closes #2411
Tabs component in the docs has TypeError in TypeScript.
TypeError for TypeScript.
Created an example for TS as well.
https://github.com/nextui-org/nextui/assets/62743644/3a1b4d16-9503-4a62-8451-64c978ba00f6
No.
> docs(components): type error on tab components

- apps/docs/.env.example
- apps/docs/app/layout.tsx
- apps/docs/components/docs/sidebar.tsx
- apps/docs/components/featurebase/fb-changelog-button.tsx
- apps/docs/components/featurebase/fb-feedback-button.tsx
- apps/docs/components/featurebase/fb-roadmap-link.tsx
- apps/docs/components/navbar.tsx
- apps/docs/config/routes.json
- apps/docs/utils/featurebase.ts
Closes # 
- integrate featurebase (only show roadmap currently)
- please add `NEXT_PUBLIC_FB_FEEDBACK_ORG` and `NEXT_PUBLIC_FB_FEEDBACK_URL` to your `.env`
> feat: featurebase integration

- .changeset/chilled-cups-tell.md
- packages/hooks/use-aria-multiselect/src/use-multiselect-list-state.ts
Closes # 
#2346 
Fix #2346 
No
> fix: won't display warning in when placeholder (#2346)

- CONTRIBUTING.md
> fix: Invalid command

- packages/components/link/stories/link.stories.tsx
> fix(stories): link anchor typo

- .changeset/wild-rockets-check.md
- packages/core/theme/src/components/modal.ts
Closes # 
Add RTL support to the modal component.
The modal component currently lacks support for right-to-left (RTL) direction.
This PR addresses the RTL support issue in the modal component, ensuring correct rendering in RTL environments.
Resolves issue https://github.com/nextui-org/nextui/issues/2414
> fix: add RTL support to the modal component

- .changeset/orange-beds-mix.md
- .changeset/purple-keys-dance.md
- packages/core/theme/src/components/toggle.ts
Closes #2467
Add RTL support to the switch component.
The switch component currently lacks support for right-to-left (RTL) direction.
This PR addresses the RTL support issue in the switch component, ensuring correct rendering in RTL environments.
close #2467
> Add RTL support to the switch component 

- .changeset/serious-sheep-promise.md
- packages/core/theme/src/components/kbd.ts
Closes #2481
Add RTL support to the kbd component.
The kbd component currently lacks support for right-to-left (RTL) direction.
This PR addresses the RTL support issue in the kbd component, ensuring correct rendering in RTL environments.
> fix(kbd): add RTL support to the kbd component (#2481)

- apps/docs/app/layout.tsx
- apps/docs/components/scripts/script-providers.tsx
> feat(docs): Integrate kapaai

- packages/components/badge/src/badge.tsx
Closes # 
Remove unused import statement in `badge.tsx` 
> chore(badge): remove unused import statement in badge.tsx

- packages/components/calendar/__tests__/calendar.test.tsx
- packages/components/calendar/__tests__/range-calendar.test.tsx
- packages/components/calendar/src/calendar-context.ts
- packages/components/calendar/src/calendar-header.tsx
- packages/components/calendar/src/calendar.tsx
- packages/components/calendar/src/index.ts
- packages/components/calendar/src/range-calendar.tsx
- packages/components/calendar/src/use-calendar-base.ts
- packages/components/calendar/src/use-calendar-picker.ts
- packages/components/calendar/src/use-range-calendar.ts
- packages/components/calendar/stories/range-calendar.stories.tsx
- packages/components/switch/src/use-switch.ts
- packages/core/theme/src/components/calendar.ts
- packages/utilities/test-utils/src/constants.ts
- packages/utilities/test-utils/src/events.ts
- packages/utilities/test-utils/src/index.ts
> Range Calendar 📆

- packages/components/select/src/use-select.ts
> fix(select): only trigger setSelectedKeys when domRef.current.value is true

- apps/docs/content/docs/api-references/nextui-provider.mdx
> feat(docs): add example how to set locale

- apps/docs/content/components/input/regex-validation.ts
- apps/docs/content/docs/components/input.mdx
> chore(docs): supplement errorMessage behaviour in input

- .changeset/plenty-bags-brush.md
- packages/core/theme/src/components/skeleton.ts
> fix(theme): add missing pointer event after data loaded

- apps/docs/components/marketing/custom-themes/styles.ts
> docs: padding error in card

- packages/components/autocomplete/__tests__/autocomplete.test.tsx
> chore(autocomplete): should blur after clicking outside autocomplete

- .changeset/wild-jobs-explain.md
- packages/hooks/use-image/src/index.ts
Closes # 
Image is browser-specific object. won't work in ssr.
> fix(use-image): Image ReferenceError in SSR

- .changeset/kind-insects-end.md
- packages/hooks/use-image/__tests__/use-image.test.tsx
- packages/hooks/use-image/package.json
- packages/hooks/use-image/src/index.ts
- pnpm-lock.yaml
> fix: image loading in the server

- .changeset/moody-rabbits-shop.md
- packages/components/calendar/src/calendar-month.tsx
- packages/components/calendar/src/calendar-picker.tsx
- packages/components/tabs/src/tab-panel.tsx
- packages/utilities/shared-utils/src/functions.ts
> fix: support inert value with boolean type for react 19

- apps/docs/content/components/skeleton/loaded.raw.jsx
- apps/docs/content/components/skeleton/loaded.ts
- apps/docs/content/components/skeleton/standalone.raw.jsx
- apps/docs/content/components/skeleton/standalone.ts
- apps/docs/content/components/skeleton/usage.raw.jsx
- apps/docs/content/components/skeleton/usage.ts
> refactor(docs): skeleton dx

- apps/docs/content/components/spacer/usage.raw.jsx
- apps/docs/content/components/spacer/usage.ts
> refactor(docs): spacer dx

- apps/docs/content/components/snippet/colors.raw.jsx
- apps/docs/content/components/snippet/colors.ts
- apps/docs/content/components/snippet/custom-icons.raw.jsx
- apps/docs/content/components/snippet/custom-icons.ts
- apps/docs/content/components/snippet/custom-tooltip.raw.jsx
- apps/docs/content/components/snippet/custom-tooltip.ts
- apps/docs/content/components/snippet/multiline.raw.jsx
- apps/docs/content/components/snippet/multiline.ts
- apps/docs/content/components/snippet/sizes.raw.jsx
- apps/docs/content/components/snippet/sizes.ts
- apps/docs/content/components/snippet/symbol.raw.jsx
- apps/docs/content/components/snippet/symbol.ts
- apps/docs/content/components/snippet/usage.raw.jsx
- apps/docs/content/components/snippet/usage.ts
- apps/docs/content/components/snippet/variants.raw.jsx
- apps/docs/content/components/snippet/variants.ts
- apps/docs/content/components/snippet/without-copy.raw.jsx
- apps/docs/content/components/snippet/without-copy.ts
> refactor(docs): snippet dx

- apps/docs/content/components/scroll-shadow/custom-size.raw.jsx
- apps/docs/content/components/scroll-shadow/custom-size.ts
- apps/docs/content/components/scroll-shadow/hide-scrollbar.raw.jsx
- apps/docs/content/components/scroll-shadow/hide-scrollbar.ts
- apps/docs/content/components/scroll-shadow/horizontal.raw.jsx
- apps/docs/content/components/scroll-shadow/horizontal.ts
- apps/docs/content/components/scroll-shadow/offset.raw.jsx
- apps/docs/content/components/scroll-shadow/offset.ts
- apps/docs/content/components/scroll-shadow/usage.raw.jsx
- apps/docs/content/components/scroll-shadow/usage.ts
> refactor(docs): scroll-shadow dx

- apps/docs/content/components/kbd/keys.raw.jsx
- apps/docs/content/components/kbd/keys.ts
- apps/docs/content/components/kbd/usage.raw.jsx
- apps/docs/content/components/kbd/usage.ts
> refactor(docs): kbd dx

- apps/docs/content/components/autocomplete/colors.raw.jsx
- apps/docs/content/components/autocomplete/controlled.raw.jsx
- apps/docs/content/components/autocomplete/controlled.raw.tsx
- apps/docs/content/components/autocomplete/custom-empty-content-message.raw.jsx
- apps/docs/content/components/autocomplete/custom-filtering.raw.jsx
- apps/docs/content/components/autocomplete/custom-filtering.raw.tsx
- apps/docs/content/components/autocomplete/custom-selector-icon.raw.jsx
- apps/docs/content/components/autocomplete/custom-value.raw.jsx
- apps/docs/content/components/autocomplete/description.raw.jsx
- apps/docs/content/components/autocomplete/disabled-items.raw.jsx
- apps/docs/content/components/autocomplete/disabled.raw.jsx
- apps/docs/content/components/autocomplete/dynamic.raw.jsx
- apps/docs/content/components/autocomplete/error-message.raw.jsx
- apps/docs/content/components/autocomplete/events.raw.jsx
- apps/docs/content/components/autocomplete/events.raw.tsx
- apps/docs/content/components/autocomplete/fully-controlled.raw.jsx
- apps/docs/content/components/autocomplete/fully-controlled.raw.tsx
- apps/docs/content/components/autocomplete/label-placements.raw.jsx
- apps/docs/content/components/autocomplete/read-only.raw.jsx
- apps/docs/content/components/autocomplete/required.raw.jsx
- apps/docs/content/components/autocomplete/sizes.raw.jsx
- apps/docs/content/components/autocomplete/start-content.raw.jsx
- apps/docs/content/components/autocomplete/usage.raw.jsx
- apps/docs/content/components/autocomplete/variants.raw.jsx
- apps/docs/content/components/autocomplete/without-scroll-shadow.raw.jsx
Closes # 
The example has been updated because specifying `value` was [causing confusion](https://github.com/nextui-org/nextui/pull/3375#issuecomment-2483421983
).
See: https://github.com/nextui-org/nextui/pull/2937#discussion_r1590213601
> refactor(docs): autocomplete dx rename value to key

- apps/docs/content/components/image/blurred.raw.jsx
- apps/docs/content/components/image/blurred.ts
- apps/docs/content/components/image/fallback.raw.jsx
- apps/docs/content/components/image/fallback.ts
- apps/docs/content/components/image/loading.raw.jsx
- apps/docs/content/components/image/loading.ts
- apps/docs/content/components/image/nextjs.raw.jsx
- apps/docs/content/components/image/nextjs.ts
- apps/docs/content/components/image/usage.raw.jsx
- apps/docs/content/components/image/usage.ts
- apps/docs/content/components/image/zoomed.raw.jsx
- apps/docs/content/components/image/zoomed.ts
> refactor(docs): image dx

- apps/docs/content/components/spinner/colors.raw.jsx
- apps/docs/content/components/spinner/colors.ts
- apps/docs/content/components/spinner/label-colors.raw.jsx
- apps/docs/content/components/spinner/label-colors.ts
- apps/docs/content/components/spinner/label.raw.jsx
- apps/docs/content/components/spinner/label.ts
- apps/docs/content/components/spinner/sizes.raw.jsx
- apps/docs/content/components/spinner/sizes.ts
- apps/docs/content/components/spinner/usage.raw.jsx
- apps/docs/content/components/spinner/usage.ts
> refactor(docs): spinner dx

- .changeset/curly-rules-warn.md
- packages/components/calendar/package.json
Closes # 
as titled.
ref: #4139
> fix(deps): add missing `framer-motion` in `peerDependencies`

- apps/docs/components/docs/toc.tsx
- apps/docs/config/routes.json
- apps/docs/content/docs/guide/form.mdx
- apps/docs/content/docs/guide/routing.mdx
> docs: add forms guide

- .changeset/tiny-laws-cheer.md
- packages/core/system/src/provider.tsx
Closes # 
The current parameter is outdated. Align with the latest one used in react-aria.
> fix(system): align navigate function parameters

- .github/workflows/enter-pre-release-mode.yaml
> fix: pre release workflow on protected branches

- .changeset/few-ants-breathe.md
- packages/components/input-otp/package.json
> fix: input otp peer deps

- .github/workflows/pre-release.yaml
> chore: pre release workflow modified

- .github/workflows/pre-release.yaml
> fix: pre-release workflow

- apps/docs/components/docs/components/helper.ts
> chore(docs): revise defaultShowFlagList

- .changeset/lovely-news-camp.md
> fix: snippet release

- .changeset/nice-beds-battle.md
> fix(changeset): incorrect package name

- apps/docs/content/docs/components/tabs.mdx
Closes #4814 
Corrected the `Tab` usage example to reflect the correct prop (`key` instead of `id`).
> fix(docs): correct Tab usage example

- .changeset/config.json
> fix(changeset): remove `@heroui/stories-utils` and `@heroui/test-utils` from ignore list

- apps/docs/content/components/toast/usage.raw.jsx
- packages/components/toast/stories/toast.stories.tsx
> fix: shouldShowTimeoutProgress typo

- .changeset/curvy-poets-study.md
- apps/docs/package.json
- packages/core/system-rsc/package.json
- packages/core/theme/package.json
- pnpm-lock.yaml
> fix: revert to use previous version

- packages/core/theme/src/animations/index.ts
- packages/core/theme/src/components/image.ts
- packages/core/theme/src/components/skeleton.ts
> fix: animate about skeleton

- apps/docs/content/blog/v2.3.0.mdx
- apps/docs/content/docs/frameworks/astro.mdx
- apps/docs/content/docs/frameworks/laravel.mdx
- apps/docs/content/docs/frameworks/nextjs.mdx
- apps/docs/content/docs/frameworks/remix.mdx
- apps/docs/content/docs/frameworks/vite.mdx
- apps/docs/content/docs/guide/installation.mdx
- apps/docs/content/docs/guide/tailwind-v4.mdx
Closes # 
This PR is to
- update the doc link for TW 4
- supplement "Update CSS Import" with / without `tailwind.config.js` usage
> chore(docs): update TW v4 doc

- apps/docs/components/sandpack/entries.ts
- apps/docs/components/sandpack/use-sandpack.ts
- apps/docs/hooks/use-stackblitz.ts
- packages/storybook/package.json
- pnpm-lock.yaml
> fix: open in remote repo

- .changeset/lazy-camels-clap.md
- packages/components/button/src/use-button.ts
Closes #5200
Currently clicking icon in button will make it show the focus ring which is not expected.
> fix(button): icon focus behaviour on click

- packages/core/theme/src/components/select.ts
> fix: select translate styles

- .changeset/poor-experts-leave.md
- packages/core/theme/src/utilities/transition.ts
> fix(theme): transition scale

- packages/core/theme/src/utils/tw-merge-config.ts
> fix: transition autocomplete

- packages/core/react/README.md
> chore: remove ph banner

- packages/components/toast/src/index.ts
> chore(toast): export getToastQueue

- .lintstagedrc.cjs
> fix: handle files with paths containing empty space

- .changeset/chilly-garlics-lick.md
- apps/docs/components/sandpack/use-sandpack.ts
- apps/docs/package.json
- packages/core/theme/package.json
- packages/storybook/package.json
- pnpm-lock.yaml
Closes #!-- Github issue # here -->
> chore(deps): bump tailwindcss version

- apps/docs/.env.example
- apps/docs/env.ts
- apps/docs/src/utils/env.ts
- turbo.json
Closes # 
Use `www.heroui.com / v3.heroui.com` for reliable meta base and og-image generation
N/A
N/A
No
> fix(docs): use production url for reliable meta base

- .vscode/settings.json
- packages/styles/components/avatar.css
- pnpm-lock.yaml
- prettier.config.mjs
Closes # 
Fixed layout of avatar image
N/A
N/A
No.
> fix(avatar): layout of avatar image

- packages/styles/themes/default/variables.css
Closes # 
Fixed `success` variant in dark mode.
N/A
N/A
No.
> fix(chip): success variant in dark mode

- packages/styles/components/switch.css
> refactor(styles): switch control & thumb
