packages/nextui/src/input/input-icon-clear.tsx
packages/nextui/src/input/input.tsx

#61
Position `relative` added when input has content at right, also the height was changed to `auto`

fix: icon position when has contentRight 

---

packages/docs/src/components/playground/editor.tsx

#64 
Display mode changed to `none` when live-editor is not open and `flex-inline` when it is

fix: options buttons only shows up when the live editor is open

---

packages/nextui/src/checkbox/checkbox.tsx

**TASK**: [Small Checkbox is not rendering well #68 ](https://github.com/nextui-org/nextui/issues/68)
I've add a new css line for pseudo element checkbox icon to prevent a bad rendering of the lines that creates the checkbox ticket. Keeping the same look and feel that before.

Fix checkbox icon pseudo element (fix #68)

---

packages/nextui/src/avatar/avatar.tsx

**TASK**: [Fix avatar image resize](https://github.com/nextui-org/nextui/issues/104)
Resize large images to cover the avatar

Fix 104/avatar resize img

---

apps/docs/content/docs/theme/dark-mode.mdx

Minor fix which fixes an issue
Solved syntax error when can't get `SwitchEvent` in [this file](https://github.com/nextui-org/nextui/blob/main/apps/docs/content/docs/theme/dark-mode.mdx).
```javascript
export interface SwitchEvent {
target: SwitchEventTarget;
stopPropagation: () => void;
preventDefault: () => void;
nativeEvent: React.ChangeEvent;
}
```

Update dark-mode.mdx | Fixed wrong function argument :v:

---

apps/docs/content/docs/theme/dark-mode.mdx

Altered onChange callback of Switch component in the Dark Mode page from the docs. 'e.target' is altered to 'e.target.checked'.
**TASK**:

fix(docs): dark mode switch onchange

---

packages/react/src/text/text.tsx

**TASK**:  [Warning: Received false for a non-boolean attribute `sm`.](https://github.com/nextui-org/nextui/issues/161)
This PR fixes issue 161. The problem was the `defaultProps` object which was having a `sm` key rather than `small`.
No visual change was made.

fix issue 161

---

apps/docs/content/docs/components/collapse.mdx
apps/docs/src/components/home/built-in-stitches.tsx
packages/react/src/collapse/__tests__/index.test.tsx
packages/react/src/collapse/collapse.stories.tsx
packages/react/src/collapse/collapse.tsx

**TASK**:  https://github.com/nextui-org/nextui/issues/162
I just replace `initialExpanded` to `expanded`, to be able to use this prop as a trigger to make changes in the state

fix(collapse): manage expand behavior by prop

---

apps/docs/content/docs/layout/container.mdx
apps/docs/content/docs/layout/grid.mdx
apps/docs/content/docs/layout/spacer.mdx

Nice work folks! I'm already starting a project using this lib
I got a small layout bug, just an extra space to match everything else.
Just a  ```<Spacer y={2} />``` component was added under the  ```<CarbonAd />``` to follow the pattern of the other pages.

fix(docs): space added to layout section top

---

apps/docs/src/components/templates/shop-card/styles.ts

NO TASK
Fix responsive for the card demo on the home page.

fix responsive for ipad-h on home page

---

apps/docs/src/components/hero/styles.ts
apps/docs/src/components/primitives/index.ts
packages/react/src/theme/common.ts

**TASK**: This PR Fixes #215 
The Root Cause of this issue was that Gradient Component By Default Class was Set as Transparent which was causing Highlighted Part to Go Transparent too with Background Gradient . ~~This was NextUI Component Based Issue hence this PR Fixes on PR on fixing every Gradient Component~~
Latest Commit :- After the Latest Commit Changes are only applied to main website
Before :-
After :-

Fixed Invisible Gradient Component When Highlighting it

---

packages/react/src/theme/utils.ts

**TASK**: [308](https://github.com/nextui-org/nextui/issues/308)
I added an extra condition to avoid empty strings in this case the next map wouldn't add the semicolon when string is empty.
It avoid to add unnecessary semicolons in document style tag.

fix: changeTheme function to avoid empty strings

---

packages/react/src/tooltip/tooltip.stories.tsx
packages/react/src/tooltip/tooltip.styles.ts

**TASK**: #322 
Tooltip content don't have define invert
Previous 
Now

Fix ( Tooltip) Text invert's color error

---

apps/docs/content/docs/components/link.mdx
apps/docs/content/docs/components/text.mdx

**TASK**: `null`
Just found some new heading issues.
I'm not sure if I used the correct heading names or not, so please check them before merging.
Thanks <3

[docs] fix some `text` & `link` types/props headings

---

apps/docs/content/docs/components/button.mdx
packages/react/src/button/button.tsx

**TASK**: https://github.com/nextui-org/nextui/issues/274
Add type to defaultProps of Button component
Change the default of type props in the Button component documentation to `button`

fix(button): Change the default of Button type props

---

packages/react/src/backdrop/backdrop.styles.ts
packages/react/src/backdrop/backdrop.tsx

**TASK**: https://github.com/nextui-org/nextui/issues/288
Add the same opacity animation to `BackdropContent` as the `Modal`
https://user-images.githubusercontent.com/32772271/160436312-eb261bcf-21cf-48df-8c9e-5a1b528a83d8.mov

Fix #288 modal animation behavior

---

.github/pull_request_template.md
apps/docs/content/components/popover/placements.ts
packages/react/src/grid/grid-container.tsx

Closes #427 
- Missing `Text` component added to the Popover docs placements section
- Pull request template changed

Fix 427/missing component popover docs

---

apps/docs/content/components/popover/custom-content.ts

Remove unnecessary import from [popover custom content](https://nextui.org/docs/components/popover#custom-content)  example
doc: `apps/docs/content/components/popover/custom-content.ts`
```diff
- import { useTheme, Text, Button, Grid, Row } from "@nextui-org/react";
+ import { Text, Button, Grid, Row } from "@nextui-org/react";
```
```diff
- Are you sure you want to delete this user ?, by doing this, you will
+ Are you sure you want to delete this user ? By doing this, you will
```

docs: remove unnecessary import from popover example

---

packages/react/package.json
yarn.lock

Closes https://github.com/nextui-org/nextui/issues/291
Fix the `length is declared here` issue by upgrading stitches to version [1.2.8](https://github.com/modulz/stitches/releases/tag/v1.2.8)
```diff
- "@stitches/react": "1.2.7"
+ "@stitches/react": "1.2.8"
```
Screenshot of code completion with latest typescript **`CSS property`**
Screenshot of code completion with latest typescript **`Stitches utils`**

fix: #291 stitches compatability with typescript

---

apps/docs/content/docs/theme/typescript.mdx

Fix createTheme Typings in docs

---

packages/react/src/card/card.styles.ts
packages/react/src/theme/common.ts

Removed auto margin for first and last Card item

fix(react-card):  :first-child/:last-child margin was removed

---

packages/react/src/link/link.tsx

Closes # 
Due to [next/link](https://nextjs.org/docs/api-reference/next/link) doesn't support multiple children we have to wrap the NextUI children into a fragment
It's not possible to use the NextUI link as a next/link thought the `as` prop
NextUI children were wrapped into a React Fragment in order to support [next/link](https://nextjs.org/docs/api-reference/next/link), NextUI will be able to use it as follows:
```js
import NextLink from "next/link";
import { Link } from "@nextui-org/react"
export default function App() {
return (
<Link href="#" as={NextLink}>
"First solve the problem. Then, write the code." - Jon Johnson.
</Link>
);
}
```

fix(react-link): wrap it into a single child

---

packages/react/src/button/button.tsx

Closes #426 
The button component is not dispatching the `onClick` event, a temporal solution was implemented until we fully migrate to the `useButton` props
The button component is not dispatching the `onClick` event
A temporal solution was implemented until we fully migrate to the`useButton` props

Fix 426/button onclick keyboard

---

packages/react/src/checkbox/checkbox.tsx

Closes #431 
Checkbox's `initialChecked` prop was being passed to the html
React doesn't recognize the `initialChecked` prop on a DOM element
The `initialChecked` prop was taken out from the checkboxProps, this prop will be renamed to `defaultSelected` in a near future
The `initialChecked`  will be renamed to `defaultSelected` in a near future to have a better `@react-aria` integration

Fix 431/checkbox initial checked

---

apps/docs/src/components/hero/index.tsx
apps/docs/src/components/mobile-navigation/index.tsx
apps/docs/src/components/primitives/index.ts
apps/docs/src/components/search/autocomplete.tsx
apps/docs/src/layouts/styles.ts
packages/react/src/backdrop/backdrop.styles.ts
packages/react/src/modal/modal.stories.tsx

Closes #456 
Due to the `backdrop-filter` property doesn't work on firefox, a workaround was implemented
Blurred parts are displayed with transparency only on Firefox
- docs: Navbar, Search box, Cards and other elements were modified to display a solid color instead of a blurred background on Firefox
- modal: The backdrop component was modified to display a background with transparency instead of a blurred background, only on Firefox (or browsers where the `backdrop-filter` property is not supported)

Fix 456/unblurred menu bar firefox

---

apps/docs/content/landing/index.tsx
apps/docs/src/components/templates/custom-button/index.tsx
apps/docs/src/pages/_document.tsx

Closes https://github.com/nextui-org/nextui/issues/468
Fix the confetti position in the landing page.
Correct the confetti position by click event.
Remove the confetti positioning code from example and focus on the topic.
No
Screenshot of confetti with better position

fix(docs-landing): confetti position

---

apps/docs/content/components/card/cover.ts
apps/docs/content/docs/theme/utilities.mdx
apps/docs/content/landing/index.tsx
packages/react/src/card/card.stories.tsx
packages/react/src/theme/common.ts

Amends the Stitches utility function `bgBlur` to set the passed background-color value as-is instead of appending `66` (for alpha), which only works for hex color codes.
This change enables passing other color code formats, like `hsla()` and `rgb()`, and color tokens just like the rest of NextUI. The previous implementation confuses users for why their color value does not work.
Second, the previous implementation of setting the passed color alpha to 66% is hidden from the user. If the user wants to pass a value with a particular alpha that is not 66%, she must think about the additional 66% modification happening to her color.
For example, I would like to set the background color for this blur effect to exactly `hsla(0, 0%, 100%, 0.1)`, where I can easily tweak the alpha value. However, …

theme: Amend utility function `bgBlur` to not modulate background value

---

packages/storybook/.storybook/preview.js

Storybook theme switching with NextUI.
- Fullscreen canvas
- Correct the theme class
- Use NextUI radii `xs`
- Use NextUI color `accents`
No
Screenshot of light theme
Screenshot of dark theme

feat(storybook): theme toggle with nextui

---

apps/docs/src/layouts/navbar.tsx

Closes https://github.com/nextui-org/nextui/issues/489
Fix navbar background transparent after scroll down and refresh.
Set `scrollPosition` when `navbar` component mounted.
No
Screenshot after scrolling down and refreshing

fix(docs): navbar background transparent after refresh

---

apps/docs/src/styles/globalStyles.ts

When clicking any section title (rendered by `LinkedHeading()`) in doc, the page jump to where a part of the section is hiding behind the navbar.
This is a common problem caused by sticky navbar, which can be solved by CSS scroll snap module.
Note that Size section actually hides behind navbar.

Prevent anchor links from hiding behind navbar

---

packages/react/src/user/index.ts
packages/react/src/user/user-link.tsx
packages/react/src/user/user.styles.ts
packages/react/src/user/user.tsx

Closes https://github.com/nextui-org/nextui/issues/474
- passed unnecessary props to `StyledUser`
> `Warning: Received true for a non-boolean attribute zoomed`
> `Warning: Received true for a non-boolean attribute pointer`
- `StyledUserLink` and `Link` both use the `a` tag
> `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>`
- structure `props` in order to pass the correct `otherProps`
- change the `a` tag of `StyledUserLink` to `span`
No

fix(react-user): prop and link warnings

---

apps/docs/content/components/container/autoLayout.ts
apps/docs/content/components/container/breakpoint.ts
apps/docs/content/components/container/default.ts
apps/docs/content/components/container/fluid.ts
apps/docs/content/components/grid/autoWidth.ts
apps/docs/content/components/grid/default.ts
apps/docs/content/components/grid/fluid.ts
apps/docs/content/components/grid/hideElement.ts
apps/docs/content/components/grid/responsive.ts
apps/docs/content/components/spacer/horizontal.ts
apps/docs/content/components/spacer/vertical.ts

The `Card` in the Layout docs is not updated with the new APIs.
- Wrapped `Card` in `Card.Body`
- Add card background color as `primary`
No

fix(docs-layout): wrapped card in card.body and added background color

---

apps/docs/content/docs/components/card.mdx
apps/docs/content/docs/components/checkbox-group.mdx
apps/docs/content/docs/components/checkbox.mdx
apps/docs/content/docs/components/dropdown.mdx
apps/docs/content/docs/components/popover.mdx
apps/docs/content/docs/components/radio.mdx
apps/docs/content/docs/components/table.mdx
apps/docs/content/docs/components/textarea.mdx
apps/docs/content/docs/theme/dark-mode.mdx
apps/docs/content/docs/theme/default-theme.mdx
apps/docs/content/docs/theme/media.mdx
apps/docs/content/docs/theme/override-styles.mdx
apps/docs/content/docs/theme/utilities.mdx

Bolded keywords in blockquotes.
- Bold keywords
- Accessibility to A11y
- Duplicate `Note` in `Radio` docs
No

chore(docs): bolded keywords in blockquotes

---

apps/docs/content/docs/components/dropdown.mdx

Some dropdown component APIs in doc are not exposed to users currently.
Do we have a plan to support them in the future?

doc: remove unavailable apis

---

packages/react/src/card/card.tsx

Texts on card components can not be selected by mouse when they are not pressable.
Texts can not be selected nor copied.
Texts can be selected and copied.
This is a bug invoked by react-aria `usePress`. According to the author of `usePress()` ([explained here](https://github.com/adobe/react-spectrum/issues/2956#issuecomment-1069655946), which also involved the card implementation), we should avoid it when the card is not pressable. Correct me if I'm wrong 😂 not a pro of react-aria

fix: card text selection

---

packages/react/src/card/card.stories.tsx
packages/react/src/card/card.tsx
packages/react/src/card/use-card.ts

This PR solve the card internal components hover/focus/click issue.
Currently users can't hover/focus/click the card internal components.
`pressProps`, `focusProps` and `hoverProps` are now being conditionally applied to the card depending on whether the `isPressable` and `isHoverable` props are set to `true`.

fix(react-card): internal components hover and text copy

---

packages/react/src/spacer/spacer.stories.tsx

Spacer component storybook not working.
Spacer storybook prompted
```
undefined is not an object (evaluating 'theme.palette.primary')
```
Theme object is correctly imported and storybook works.

fix(react-spacer): spacer stories

---

apps/docs/content/docs/guide/nextui-plus-nextjs.mdx

When trying to replicate the example it will fail since in the example the React instance is being requested in:
```jsx
return {
...initialProps,
styles: React.Children.toArray([initialProps.styles])
//                  ^
};
}
```
and this at no time matters
Closes # 
> When trying to replicate the example it will fail since in the example the React instance is being requested and this at no time matters
> I add the line import React from 'react'
At the time of following the steps and copying and pasting the example, this error will stop appearing
It's something simple that users can add, but for novice programmers it can be a headache to understand what is going wrong, and the idea that the learning curve or creating your project can …

Need Import React in Example

---

apps/docs/content/docs/components/avatar.mdx

Fix the docs from `false` to `true` because it is `animated: true` in avatar-group
No
Fix the avatar-group.styles.ts file if the default value assumes false

fix(docs):default value of animated props in avatar group

---

apps/docs/content/docs/components/dropdown.mdx

Closes #585
`onAction` & `onClose` are currently not `Dropdown.Item` props and may lead to confusion.

fix(doc): remove unimplemented Dropdown API

---

packages/react/src/container/container.tsx

Closes [#566 ](https://github.com/nextui-org/nextui/issues/566)
Allow passing `ref` to Container
Doesn't allow to pass `ref`.
Allows passing `ref`.
No

feat(react-container): add forwardRef

---

packages/react/src/table/table.tsx
packages/react/src/utils/prop-types.ts

Closes [#557  ](https://github.com/nextui-org/nextui/issues/557)
It's not possible to replicate the same issue locally in storybook, but I noticed that some props from @react-stately/table hook `useTableState` were being wrongly spread into `StyledTable`. That's why the dom was complaining regarding the `onSelectionChange`, because that event does not exist natively.
I'm not changing any behaviour, just strictly passing the correct props.
No new behaviour.
No.
Would be nice to understand why the storybook instance is suppressing this error.
@jrgarciadev, let me know if you agree with my commit text.

fix(react-table): react-stately props

---

apps/docs/content/docs/components/table.mdx

Fixes a typo in the Table docs.

docs: fix typo in the Table docs

---

apps/docs/content/components/table/custom-cells.ts

Closes https://github.com/nextui-org/nextui/issues/653
Remove wrong imports in custom cells example.
No

fix(docs): remove wrong imports in custom cells example

---

apps/docs/content/components/navbar/common.ts
packages/react/src/input/index.ts
packages/react/src/input/input.tsx

Closes #707 
Circular dependency between the `input` and `Textarea` components
#707 
`Textarea` import was removed from the `Input` files
If you are using the `Input.Textarea` compound component, you should migrate to `Textarea`

Fix 707/textarea input circular dependecy

---

packages/react/src/use-pagination/index.ts

Closes https://github.com/nextui-org/nextui/issues/619
Reading `state` in pagination's `onChange` will always return the initial value.
Add `activePage` to the memoized callback deps.
Update or changes if `total, activePage` (deps) has been changed.
Read more: [`usecallback`](https://reactjs.org/docs/hooks-reference.html#usecallback).
No
> **Note** The branch based on `next`.

fix(react-pagination): add active page to memoized callback deps

---

apps/docs/content/docs/components/switch.mdx
packages/react/src/switch/switch.stories.tsx
packages/react/src/switch/switch.tsx

Useful when a switch appears in a form with conjunction with formData.
Add's the ability to pass in the `name` prop to `<Switch/>`, and passes it to the `input` element created inside the component. Doing this allows us to get the value using formData instead of relying on state controlled toggle. 
Cannot pass `name` prop to Switch so that the input has a name. 
`<Switch name={"helloWorld"}/>` will render `<input name={"helloWorld"] ...restOfTheObject/>`. This is useful for when placing a Switch instead of a form, and need to extract the value with formData instead of using state + controlled.
no

Add name to switch input element.

---

apps/docs/content/components/card/action.ts
packages/react/src/card/card.stories.tsx

Closes #792
There are typos in the Card Component docs:
1. The word "Raspberry" bellow the picture of a Cherry, changed it to "Cherry".
2. The word "Advocato", changed it to "Avocado"
Also fixed both typos in the storybook for the card component.

Fix typos in card component docs and storybook (fix #792)

---

apps/docs/content/components/link/icon.ts

Closes # 
Change prop `icon` to `isExternal` in the Playground.
The <Link> components should be using the isExternal prop instead of icon.
[Issue 777](https://github.com/nextui-org/nextui/issues/777)
No

fix(docs): playground `isExternal` in link component

---

packages/react/src/tooltip/__test__/index.test.tsx
packages/react/src/tooltip/tooltip.stories.tsx
packages/react/src/tooltip/tooltip.tsx

Closes #683
- feature: Add isDisabled property to tooltip. #683
- fix: props.content display errors
- Test Code: 
```tsx
export const WithoutContent = () => {
return (
<Container>
<Tooltip color="primary" content={0}>
<Button auto flat>
Do hover here
</Button>
</Tooltip>
</Container>
);
};
```
- Incorrect display
- Code
```tsx
{content && <TooltipContent {...contentProps}>{content}</TooltipContent>}
```
Normal display and disable requirements.
No

feat: Add isDisabled property to tooltip &  Fix abnormal props.content display #683

---

packages/react/src/radio/index.ts
packages/react/src/radio/radio.tsx

Closes https://github.com/nextui-org/nextui/issues/759
- Export `radio` and `radio-group` prop types
- Fix duplicate class names
No

fix(react-radio) inaccessible prop types and duplicate class name

---

packages/react/src/card/card.styles.ts

Closes #727 
Drop shadow was causing an issue with the footer blur on Firefox.
Footer blur not working.
Footer blur working on Firefox
No

fix(react-card): footer blur not working on Firefox

---

packages/react/src/navbar/navbar-link.tsx

Closes # 
[https://github.com/nextui-org/nextui/issues/803](https://github.com/nextui-org/nextui/issues/803)
fix: navbar link does not respect parent size in Firefox
Now the Navbar Link component uses `width: fit-content`
The result:

fix: navbar link does not respect parent size

---

packages/react/src/navbar/navbar.styles.ts

Closes #713 
BoxSizing "border-box" is causing issues on firefox and width are not being calculated properly. Probably because of using it in combination with flex components.
This PR changes box-sizing of Links and Buttons inside the NavBar to be "content-box" instead "bordex-box" which fixes the issues currently seen on Firefox
No
Only tested on Firefox and Chrome.
Need help with Safari testing.

fix(react-navbar): box-sizing causing navbar issues on firefox

---

packages/react/src/navbar/navbar.styles.ts

The collapse wrapper doesn't have a blurred background on safari
The collapse wrapper doesn't have a blurred background on safari
Safari specific styles added

fix(react-navbar): collapse wrapper background on safari

---

apps/docs/.eslintrc.json

resolve nextjs style unknown property global & jsx lint error, according to https://github.com/vercel/next.js/discussions/40269

chore: eslint ignore nextjs style unknown-property

---

packages/react/src/theme/shared-css.ts

There is a white border in the animation of the focus ring caused by the `outline` property.
- Remove `outline` styles from the `isFocusVisible` variant.
No
Take `Radio`'s focus ring as an example, however, not all components have *white border* in the animation of the focus ring.
Before:
[before.webm](https://user-images.githubusercontent.com/32772271/207093070-c151dbf5-ad23-4df8-9cfa-7a6a48703306.webm)
After:
[after.webm](https://user-images.githubusercontent.com/32772271/207093110-cbb8c72c-f3d0-42dd-aaae-6ec710611610.webm)

fix(react-theme): white border of the focus ring

---

packages/react/src/dropdown/dropdown.tsx
packages/react/src/dropdown/use-dropdown.ts

- `onClose` is not executed.
- `onOpenChange` executes twice when opening and ending with `false`.
- Solve multiple execution of `onOpenChange` by passing `OverlayTriggerProps` into `useMenuTriggerState`.
- Add `handleClose` to handle the close event.
No

fix(react-dropdown): `onClose` and `onOpenChange` events

---

packages/react/src/popover/popover-trigger.tsx

Closes https://github.com/nextui-org/nextui/issues/735
Closes https://github.com/nextui-org/nextui/issues/703
Fixed invalid event property passed into the DOM (`onPress, onPressStart`).
- Deconstructing the props of the `Button` component and custom-trigger from `triggerProps`.
No.

fix(react-popover): unknown event property when custom trigger

---

packages/react/src/popover/popover-trigger.tsx

Closes https://github.com/nextui-org/nextui/issues/649
Closes https://github.com/nextui-org/nextui/issues/969
`Popover` triggers are not triggered on mobile devices, also affected by this issue is `Dropdown`.
The issue is the wrong behavior of `onPress` in `nextUIButtonProps` 🤔 solved by passing `onPress` directly instead of handling `OverlayTriggerState` in `onPress`.
No
Related to https://github.com/nextui-org/nextui/pull/953.

fix(react-popover): popover trigger on mobile device

---

apps/docs/src/components/playground/dynamic-live.tsx

The theme of sandpack makes `DynamicLive` applied `$sm` font-size and line-height, which is the font-size and line-height of `LiveCode`.
As the live preview is not the `$base` font-size and `$md` line-height, it causes some content shift.
https://github.com/nextui-org/nextui/blob/66153ecb82e4f4b838d41763e4f83c6f8ac95c2e/apps/docs/src/components/sandpack/themes.ts#L29-L34
Reapply the right font-size and line-height to `InView`.
No
Before:
[before.webm](https://user-images.githubusercontent.com/32772271/209175226-288cfd1f-2fa4-4e3f-b8c3-886c679b5783.webm)
After:
[after.webm](https://user-images.githubusercontent.com/32772271/209175261-e579bfe0-cbd3-470c-8107-935d34029d62.webm)

fix(docs-playground): dynamic live font styles

---

packages/react/src/tooltip/tooltip.tsx

Closes #968
When setting the trigger to click, the tooltip isn't displayed even if clicked.
The `StyledTooltipTrigger` `onClick` event was not being triggered as expected, and changed it to `onClickCapture` in order to ensure that the event is correctly captured and handled.
The `onClick` event is a bubbling event, which means that it is triggered on the element that is clicked, and then it bubbles up the DOM tree to be handled by parent elements if needed. In contrast, the `onClickCapture` event is a capturing event, which means that it is triggered on the element's parent first, and then it propagates down the DOM tree to be handled by the element itself and any of its children.
By using the `onClickCapture` event instead of the `onClick` event, you can make sure that the event is …

Fix: Tooltip trigger click event

---

packages/react/src/progress/progress.styles.ts

The progress bar shows an exception.
exception: 
Correct
Setting small values makes the problem worse, as colored areas start to "highlight" circular progress bars visibly.
Display normal
No
For small values, the colored portion of the progress bar component clips out of the circular shape，
Is the design correct?

fix: process overflow visible #958

---

packages/react/src/progress/progress.tsx

Resolves the following violations:
- Elements must only use allowed ARIA attributes
- ARIA progressbar nodes must have an accessible name

fix: fixed a11y role issue in progress bar component

---

apps/docs/content/docs/theme/customize-theme.mdx

> Added the missing import `styled` to a section of the documentation code.
> The documentation used code that was not imported (`styled`).
> Documentation was missing the styled import; copying the code will now work out of the box with the new import.
No

added missing styled import

---

.eslintrc.json
.lintstagedrc.cjs
apps/docs/.eslintrc.json
package.json
packages/components/avatar/src/avatar.tsx
packages/components/checkbox/__tests__/checkbox.test.tsx
pnpm-lock.yaml

Fix the issue that lint-staged cannot be formatted automatically.
Issue key point: 
- cannot automatically remove unused imports.
- Move `eslint-plugin-prettier` to the end of the plugins list.
- New deps [`eslint-plugin-unused-imports`](https://github.com/sweepline/eslint-plugin-unused-imports) for automatic removal of unused imports.
- Turn of `no-unused-vars, unused-imports/no-unused-vars` and keep `@typescript-eslint/no-unused-vars` to detect unused vars.
No

fix: linter rules

---

packages/react/src/input/input.tsx

Closes #975 
>  When `value` in the props has changed, `selfValue` will update in `useEffect`. But `target.value` is not equal `selfValue` and it will reset the value of input element causing the cursor postposition. So, `controlledValue` should use `value` instead of `selfValue` when `isControlledComponent` is `true`.

fix: fix input cursor postposition #975

---

packages/react/src/card/card.tsx

Closes # 
While running a lighthouse test I noticed it warned about `"section"` not being valid.
Looking on [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/section_role) it looks like the correct value would be `"region"` instead.
Changes `role` from `"section"` to `"region"`.
None
No

fix: invalid role value

---

packages/react/src/textarea/utils.ts

Closes ToDo item
> Used tuple instead of the number array
>  Returns number array
> Returns labeled tuple

Used labeled tuple for CalculatedNodeHeights instead of number array

---

apps/docs/content/components/grid/hideElement.ts
apps/docs/content/components/grid/responsive.ts
apps/docs/src/hooks/use-media-query.ts
apps/docs/src/hooks/use-prefers-reduced-motion.ts

Closes # 
> Minor fix to rename two methods `addListener` and `removeListener` to `addEventListener` and `removeEventListener`
> Refer to open issue https://github.com/nextui-org/nextui/issues/1068 about the deprecated method via Typescript code.
> Renamed the deprecated methods to the new ones
> no, it does not JS, but only affects TS

fix deprecated `MediaQueryList`

---

packages/react/src/textarea/textarea.tsx

Closes #1085 
> Updated the Textarea component to properly handle resizing when controlled by an outside state controller such as `useState` or `useInput`
> The current behavior causes the form to not properly handle resizing, resulting in a scrollbar appearing no matter the props (such as `maxRows`) passed in, when such props would typically cause the Textarea to expand accordingly.
> The Textarea now correctly expands when utilizing props such as `maxRows`.
No
As a consideration, the general typing of for `value` when using an input allows for `string | string[] | number | undefined`. This PR does cause this to be assumed to be `string` which should be fine as all three of the available types are translated to `string` under the hood.

Fix: #1085 - Updated Textarea component to proper resize when controlled

---

apps/docs/src/components/nav-link/index.tsx
apps/docs/src/components/sidebar/post.tsx

This PR addresses the issue where navigation links in the sidebar for the docs app were only clickable on the link text itself. The changes make the entire area within the navigation link clickable, improving the user experience. 
Currently, the navigation links in the sidebar are only clickable on the link text itself. Clicking outside the text in the horizontal direction did not trigger the link. This can lead to a frustrating user experience, especially on mobile devices. 
[old_behavior.webm](https://user-images.githubusercontent.com/59168430/229267290-f6e5eb32-4c37-4e7e-b85d-f77d91c81d21.webm)
This PR changes the behavior. The navigation links …

fix: Make entire navigation link area clickable on sidebar for the docs app. 

---

apps/docs/content/docs/guide/getting-started.mdx
apps/docs/content/docs/guide/nextui-plus-nextjs.mdx

This PR corrects various typos in the guide documentation.

docs: fix typos in guide documentation

---

packages/core/theme/src/colors/__tests__/semantic.test.ts

```
FAIL  packages/core/theme/src/colors/__tests__/semantic.test.ts
semanticColors
light
✓ light.divider.DEFAULT has enough contrast with light.background.DEFAULT to be decorative (3 ms)
✓ light.foreground.DEFAULT has enough contrast with light.background.DEFAULT to be aa (1 ms)
✓ light.foreground.DEFAULT has enough contrast with light.default.DEFAULT to be aa (1 ms)
✓ light.default.foreground has enough contrast with light.default.DEFAULT to be aa (1 ms)
✓ light.foreground.DEFAULT has enough contrast with light.content1.DEFAULT to be aa
✓ light.content1.foreground has enough contrast with light.content1.DEFAULT to be aa
✓ light.foreground.DEFAULT has enough contrast with light.content2.DEFAULT to be aa (1 ms)
✓ light.content2.foreground has enough contrast with light.content2.DEFAULT to …
```

test: added contrast test for semantic colors

---

packages/core/theme/src/components/button.ts

Before: ![image](https://github.com/nextui-org/nextui/assets/25524993/604fc090-2fb6-4765-b37f-2c131b30be02)
After: ![image](https://github.com/nextui-org/nextui/assets/25524993/3b1dca06-de30-4bd6-81db-6ae2d19e43dc)
Before: ![image](https://github.com/nextui-org/nextui/assets/25524993/04424a9b-9fc0-4a26-9978-1cfca9709ff4)
After: ![image](https://github.com/nextui-org/nextui/assets/25524993/2bd457b4-b129-4873-b01e-7fe0e9adfb6e)
If the content is the same, the buttons are all the same size.

fix: fixed bordered button styling issues inside group

---

packages/components/tabs/__tests__/tabs.test.tsx
packages/components/tabs/src/tab.tsx

I've made improvements to the tab component by updating the HTML element from `<div>` to `<button>`. 
This change aligns with the accessibility guidelines outlined in the "Role, Property, State, and Tabindex Attributes" section of the following page: [Link to the ARIA tabs example](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/). 
By using the <button> element, we ensure better semantic representation and enhance keyboard accessibility for tab navigation.
The current behavior of the tab component is using a `<div>` element to represent each tab item.
With this change, the tab component now uses the more appropriate `<button>` element for each tab item. This improves the accessibility and ensures proper keyboard interaction with the tab navigation.
No
Using the …

 feat(tabs): improve tab accessibility

---

packages/components/pagination/src/use-pagination.ts
packages/core/theme/src/components/pagination.ts

This PR:
- removes the padding from the top and bottom (elements should not be padded IMO).
- makes it so the focus ring is not cut off anymore.
- makes it so the focus does not get lost when elements move.

fix: fixed pagination problems

---

packages/components/image/src/use-image.ts
packages/core/theme/src/components/image.ts

Closes # 
This PR fixes skeleton loading for the Image component
- Skeleton animation not showing when the image is loading
- Missing return `loading` prop in `getImgProps`
- Fix 2 issues above
- Add srcSet, sizes, crossOrigin for `useImageBase`
No

fix: fix image loading status

---

packages/components/accordion/src/accordion.tsx

Closes # 
This PR fixes `warning-keys` in Accordion components.
The following warning appear when using the Accordion component.
`Warning: Each child in a list should have a unique "key" prop.`
No warning appears.
No

fix: accordion warning keys

---

packages/components/progress/src/use-aria-progress.ts
packages/components/progress/src/use-progress.ts
packages/utilities/shared-utils/src/numbers.ts

https://storiesv2.nextui.org/?path=/story/components-progress--with-value-formatting&args=value:555
Now the label reflects the value and the progress bar is not stuck anymore.
The label is also fixed for circular progress by this change.

fix: progress bar with more than 100% is shown as full and with proper label

---

packages/components/avatar/src/avatar.tsx
packages/components/avatar/src/use-avatar.ts

https://storiesv2.nextui.org/?path=/story/components-avatar--with-image did not have an alt tag, now the alt tag falls back to `"avatar"` when `name` and `alt` is not defined.

fix: added alt fallback to avatar component

---

packages/components/tabs/src/tab.tsx

Closes #1231 
This PR fixes tabs submitting forms when clicked.
Tabs submit forms when clicked.
Tabs don't submit forms when clicked
No
None

fix: fixes tab submitting form on click

---

apps/docs/components/navbar.tsx

fix: typo navbar.tsx

---

.changeset/olive-hounds-bake.md
packages/components/tooltip/src/use-tooltip.ts

Closes https://github.com/nextui-org/nextui/issues/1168
The tooltip should not open again after the delay is not reached and the cursor moves out.
Fix the trigger behavior to prevent it from opening again after the delay is not reached and the cursor moves out.
Use `triggerProps` instead of custom on-pointer events, it already includes the correct pointer behavior.
No.
[before.webm](https://github.com/nextui-org/nextui/assets/32772271/2e1d08bc-d34c-4c85-8b9b-0341e9cd8e1b)
[after.webm](https://github.com/nextui-org/nextui/assets/32772271/f9d83313-9b6a-4098-9545-fc0ac650f289)

fix(tooltip): behavior of tooltip trigger with delay

---

.changeset/mean-parrots-whisper.md
.changeset/new-zoos-hug.md
packages/components/input/__tests__/input.test.tsx
packages/components/input/src/use-input.ts
packages/utilities/react-rsc-utils/src/filter-dom-props.ts

Closes https://github.com/nextui-org/nextui/issues/1308
This PR fixes the issue where native DOM events for the input were being triggered twice. This issue was caused by the duplication of `inputProps` and `otherProps` in the `mergeProps`.
Firstly, `inputProps` is derived from `originalProps` after being processed by `useTextField`, which already includes the native DOM events. Secondly, `otherProps` also contain a similar set of props.
In this scenario, there could be two identical DOM event functions present in `mergeProps`. However, within `mergeProps`, the identical functions are executed in a chain ([source](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/mergeProps.ts#L56)), leading to the execution of the functions twice.
Filter out duplicate …

fix(input): duplicate triggering of input events

---

.changeset/sour-lizards-allow.md
packages/components/modal/src/modal-content.tsx

This pr removes the 2px overflow from the modal in mobile view and consequently removes the scroll bar.
This was the result of visually hidden elements being 1x1px in size.

fix: moved sr only modal close buttons to not show unnecessary scroll bar

---

apps/docs/content/components/card/blurred.ts

Closes #1362
>  
> Imported CardBody instead of CardFooter. CodeSandbox now renders the preview instead of a blank screen
No

fix: fix incorrect import in blurred card

---

apps/docs/content/docs/guide/installation.mdx

> There is an error in the documentation for installing individual components on the tailwind configuration, i is specified to require @nextui-org/react but in the previous step it is indicated to install "@nextui-org/system" and "@nextui-org/theme"
> Not modifying behavior
> No new behavior
> No
> This PR is of type docs.

docs: On individual instalation instructions at tailwind setup, require package should be @nextui/theme

---

.changeset/chatty-ways-greet.md
packages/components/checkbox/src/checkbox.tsx
packages/components/checkbox/src/use-checkbox.ts
packages/components/radio/src/radio.tsx
packages/components/radio/src/use-radio-group.ts
packages/components/radio/src/use-radio.ts

Closes #1380 
Checkbox and Radio `onChange` event fixed

fix(root): checkbox and radio onChange event types fixed

---

apps/docs/content/components/card/composition.ts

Added the missing import statement for CardFooter in the code as it was not present. This fix is necessary to prevent errors for users following the documentation.
Currently, the import statement for CardFooter is missing in the code. This leads to issues for users who are following the provided documentation.
The new behavior involves including the necessary import statement for CardFooter in the codebase. This change ensures that users who follow the documentation will no longer encounter errors.
No

fix: import the cardFooter in the card component doc

---

.changeset/little-comics-report.md
packages/components/modal/src/use-modal.ts
packages/components/tooltip/src/use-tooltip.ts

Closes # 
Style prop is now being merged with the position props for the `Tooltip` component, this allows changing the `z-index`  position.

refactor(tooltip): style prop merged with the passed one

---

packages/components/select/src/select.tsx
packages/hooks/use-aria-multiselect/src/use-multiselect.ts

Before it just read out the label i.e. `Favorite Animal`, now it reads out `Dog, Favorite Animal`.
I added a visually hidden comma so most screen readers put a liddle pause between the value and label.

fix: added value to aria label of select

---

apps/docs/components/marketing/hero/floating-components.tsx
apps/docs/components/navbar.tsx

The floating Tooltip was overlapping the navbar and other elements on the home page.
I decreased its `z-index` to 39 because the navbar is `.z-40`
https://github.com/nextui-org/nextui/assets/54036572/69685a81-88ee-48e8-9e24-9c677e77ffe2
https://github.com/nextui-org/nextui/assets/54036572/5fe3bf4a-3925-4838-b89e-316a62a7f883
No

docs(tooltip): decrease zIndex so it doesn't overlap other elements

---

apps/docs/components/docs/components/component-links.tsx

> The new docs for Next.js RSC has been moved to a new section.
> The current link is redirecting incorrectly due to the recent change in the Next.js documentation.
> This PR fixes this issue by correctly adding the right link.
No.
https://github.com/vercel/next.js/commit/1dc5c066cb11a0a5e4227c84182d874f92394717

docs(components): :memo: change to the new rsc link

---

.changeset/small-badgers-look.md
packages/components/navbar/src/navbar-menu.tsx

Closes #1440 
fix unable to Close NavbarMenu
When you close and open (clicking) fastly multiple times the NavbarMenu, the Menu crashes and you are unable to close it. And you need to reload the browser to use your website!
You can close it normally.

fix(navbar): unable to Close NavbarMenu

---

.changeset/witty-trees-buy.md
packages/components/table/src/table-row.tsx

A table is still focusable in read mode and should still show a focus ring.
Steps to reproduce:
1. Open https://storybook.nextui.org/iframe.html?args=&id=components-table--static&viewMode=story
2. Press <kbd>tab</kbd>
3. Press <kbd>left</kbd><kbd>left</kbd><kbd>left</kbd><kbd>left</kbd>
Fixed:
https://github.com/nextui-org/nextui/assets/25524993/dd3b1b24-4cf1-4719-9dd7-bb24ff49ee42

fix: show focus ring when table row is focused in read mode

---

.changeset/nine-seas-smoke.md
packages/core/theme/src/components/popover.ts

Closes # 
Fix he popover and tooltip arrow color
Popover and Tooltip don't have the correct color applied to the arrow
The arrow color fixed it follows the same color passed by the user

fix(popover): arrow color

---

.changeset/three-shrimps-hope.md
apps/docs/app/examples/table/custom-styles/page.tsx
apps/docs/app/examples/table/use-case/page.tsx
apps/docs/components/code-window/code-block.tsx
package.json
packages/components/card/stories/card.stories.tsx
packages/components/table/stories/table.stories.tsx
packages/core/system/src/provider.tsx
packages/core/theme/src/types.ts
packages/hooks/use-is-mounted/package.json
pnpm-lock.yaml

Resolves https://github.com/nextui-org/nextui/issues/1494
Since the `OverlayProvider` wraps its children in a `div` container at the top level of the app, this can cause the children to not inherit the layout of the `body` element. 
While it's possible to set the layout for the container using selectors in a css file, but we could improve the DX by extending the props for `NextUIProvider` and passing them down to `OverlayProvider`. This way, we could directly set styles for the container by using `className` or `style` prop.
- Extend `NextUIProviderProps` from `ModalProviderProps` and pass these props down to `overlayProvider`.
- Update the default locale to `en-US`.
No.

feat(system): extend props for nextui provider

---

.changeset/seven-rockets-melt.md
packages/components/listbox/__tests__/listbox.test.tsx
packages/components/listbox/src/listbox.tsx
packages/components/listbox/src/use-listbox.ts
packages/components/listbox/stories/listbox.stories.tsx

Closes #1503 
Listbox dynamic items type issue
Listbox doesn't support dynamic items generic types
Generic types added to Listbox

fix(listbox): dynamic items types

---

.changeset/eighty-knives-heal.md
packages/components/pagination/src/use-pagination.ts
packages/core/theme/src/components/pagination.ts

- The cursor does not animate anymore on initial render and non page change prop changes.
- The cursor hover state now looks good with `disableAnimation` set.
- The animated cursor is now transparent to the cursor (`pointer-events: none`).

fix: resolved cursor issues in pagination

---

.changeset/mean-fishes-retire.md
packages/components/pagination/src/use-pagination.ts

For animations of the pagination cursor to be enabled `data-moving` needs to be set to `true`.

fix: fixed pagination scale animation

---

apps/docs/content/docs/components/accordion.mdx

Closes # 
This PR corrects a typo error in one of the links on the website. The link previously read "accordiom-item-classnames" and has been updated to "accordion-item-classnames" to ensure users can access the intended content without disruptions.
The current link on the website, "accordiom-item-classnames", leads to a non-existent or unintended page due to the typo.
With this PR, the link "accordion-item-classnames" will correctly direct users to the intended page.
No.
Ensuring accurate links enhances the user experience and ensures seamless navigation throughout the website.

fix(links): corrected typo in accordion link

---

packages/components/ripple/src/index.ts
packages/components/select/src/hidden-select.tsx
packages/hooks/use-aria-multiselect/src/index.ts

Related to #1595 
To prevent `src` in import path in '*.d.ts', the types should be exported in `index.ts`.
Specifically, the following error is fixed:
```
node_modules/@nextui-org/button/dist/use-button.d.ts:1:52 - error TS2307: Cannot find module '@nextui-org/ripple/src/use-ripple' or its corresponding type declarations.
1 import * as _nextui_org_ripple_src_use_ripple from '@nextui-org/ripple/src/use-ripple';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@nextui-org/card/dist/use-card.d.ts:1:52 - error TS2307: Cannot find module '@nextui-org/ripple/src/use-ripple' or its corresponding type declarations.
1 import * as _nextui_org_ripple_src_use_ripple from '@nextui-org/ripple/src/use-ripple';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```

fix: avoid `src` in import path

---

.changeset/wild-poets-sip.md
packages/utilities/react-rsc-utils/src/filter-dom-props.ts

Closes #1620 
`filterDomProps` function fixed

fix(utils): filterDomProps fixed

---

.changeset/short-eagles-sort.md
packages/components/accordion/package.json
packages/components/accordion/src/use-accordion.ts
packages/components/accordion/stories/accordion.stories.tsx
pnpm-lock.yaml

Closes #1402
Accordion is not working with controlled values
Accordion works with controlled values `selectedKeys`

fix(accordion): selectedKeys added to the values memo function

---

.changeset/fresh-cameras-provide.md
packages/components/button/src/button.tsx
packages/components/button/src/use-button.ts
packages/components/card/src/card.tsx
packages/components/card/src/use-card.ts
packages/components/ripple/src/ripple.tsx
packages/components/ripple/src/use-ripple.ts

optimize ripple destroy time, destroy it when the animation ends, not after 1 second
Destroy ripple after 1 second
Destroy ripple when the animation ends
No
I remove the `setTimeout` method, and replaced  with the `onTransitionEnd` event.

refactor: optimize the time of ripple destroy

---

.changeset/honest-yaks-attack.md
apps/docs/content/components/button/custom-impl.ts
packages/core/react/package.json
packages/core/react/src/index.ts
pnpm-lock.yaml

Closes # 
Button custom implementation example fixed

fix(docs): button custom implementation

---

.changeset/moody-fans-stare.md
packages/core/system-rsc/src/extend-variants.js

Closes #1541 
When using `extendVariants` to inherit components, if `defaultVariants` is set, it cannot be overridden. 
When using `extendVariants` to inherit components, if `defaultVariants` is set, it cannot be overridden. 
`extendVariants` function gives more priority to final component props over the `extendVariants` props

fix(core): extend variants function, destructuring order changed

---

apps/docs/content/components/listbox/custom-styles.ts
packages/components/listbox/stories/listbox.stories.tsx

<Doc Bug Fixe>
1. There was a spelling error where "WatchersIcon" was mistakenly written as "WatcherIcons" in the example code, causing an error in the CodeSandbox. This spelling mistake has been fixed.
2. In the documentation, `two necessary exports were missing`  ,and the `WatchersIcon` was mistakenly written  In the Listbox component, which caused an error in the CodeSandbox example. It has been fixed now.
codeSandBox: https://codesandbox.io/p/sandbox/hxg63x?file=/App.jsx:1,1&utm_medium=sandpack
> A bug report in code sandbox
url: https://codesandbox.io/p/sandbox/hxg63x?file=/App.jsx:1,1&utm_medium=sandpack
> fix doc : add export IconWrapper and ItemCounter
> fix doc : fix `WatchersIcons` to `WatchersIcon`  
No

fix doc: Fixed some errors in the Listbox Component documentation.

---

.changeset/hot-otters-laugh.md
packages/core/theme/src/components/radio.ts

Closes # 
When Radio is selected in invalid state, the border of the Radio controller should be danger color
````javascript
isInvalid: {
true: {
control: "bg-danger text-danger-foreground",
// data-[selected=true]:border-danger -> group-data-[selected=true]:border-danger
wrapper: "border-danger data-[selected=true]:border-danger", 
label: "text-danger",
description: "text-danger-300",
},
},
````

fix(radio): correct the style of radio in invalid and selected states

---

.changeset/chilly-trainers-type.md
packages/components/button/src/use-button.ts
packages/components/button/stories/button-group.stories.tsx
packages/core/theme/src/components/button.ts
packages/core/theme/src/utils/classes.ts

Closes #1626
The ```radius``` property does not work on the 'buttonGroup' component. The ```variant="bordered"``` option does not display the correct borders.
The ```radius``` is always the same as ```md```.
The ```border-left``` is covered by  margin-left ```ml-[calc(theme(borderWidth.medium)*-1)]```.
```tsx
<ButtonGroup color="success" radius="lg" variant="flat">
<Button>One</Button>
<Button>Two</Button>
<Button variant="bordered">Three</Button>
<Button>Four</Button>
<Button>Five</Button>
<Button>Six</Button>
</ButtonGroup>
```
The ```radius``` now works, and the border is displayed correctly in the ```buttonGroup```.
No
Please kindly let me know if any suggestions.

fix: resolved border collapse issue #1626 when border variants are mixed in button group

---

apps/docs/components/sandpack/use-sandpack.ts
apps/docs/content/components/input/custom-impl.ts

fix(docs): sandpack hook react addition validation fixed

---

apps/docs/app/docs/layout.tsx
apps/docs/components/docs/sidebar.tsx
apps/docs/components/scroll-area.tsx
apps/docs/package.json
pnpm-lock.yaml

Closes #1707
Closes #1742
Scroll Area component added to the documentation project

fix(docs): scrollbar added to the sidebar

---

apps/docs/components/docs/components/component-links.tsx

Closes # 
Currently, when you access the storybook link on the next UI component page, an error screen appears. So I fix link.
- https://storybook.nextui.org/?path=/story/components-skeleton
- https://storybook.nextui.org/?path=/story/components-skeleton--default

docs: fix storybook link in ComponentLinks

---

packages/components/slider/__tests__/drag.ts
packages/components/slider/__tests__/slider.test.tsx
packages/components/slider/src/use-slider-thumb.ts
packages/core/theme/src/components/slider.ts

Fixes https://github.com/nextui-org/nextui/pull/1686#issuecomment-1742695941
There is a bug in the slider that if both handles are placed on the right side, then they can't be draged on to another position, leaving the user stuck. There's still a way to move the handles, using the kayboard or clicking on the track, but the user may not know that those inputs work. 
Now, the last grabbed handle has the data attribute `data-focused`. Now, the user can't get stuch at an end. 
No
With this fix, it's still not possible to "swap" the handles by draging one over the other, wich would be a nice feature, but not important.
>  I came up with the solution looking at [the implementation](https://github.com/adobe/react-spectrum/blob/db43a95681e4e0f8d45d5fc6746ac3c1694bc331/packages/%40react-spectrum/sl …

fix(slider): Place last dragged slider handle over the other handle

---

.changeset/chatty-tools-invent.md
packages/components/button/src/button.tsx
packages/components/button/src/use-button.ts

The button with only icon doesn't look very good during loading, in my opinion. That's why I decided to suggest displaying only the spinner when loading is in progress.
No

fix(button): show only spinner if button isLoading & isIconOnly

---

packages/components/popover/src/use-popover.ts
packages/components/popover/stories/popover.stories.tsx

Closes #1737 
Closes #1650 
Fixing the Popover open state for blut/opaque backdrops
The Popover doesn't open on mobile devices when the backdrop is `opaque` or `blur`
The issue was fixed

Fix blur/opaque Popover

---

apps/docs/content/docs/frameworks/nextjs.mdx

Fixes typos in https://nextui.org/docs/frameworks/nextjs.

docs: Fix typos in `frameworks/nextjs.mdx`

---

.changeset/honest-plants-battle.md
packages/components/select/src/use-select.ts
packages/components/select/stories/select.stories.tsx
packages/core/theme/src/components/input.ts
packages/core/theme/src/components/select.ts

Multiline select label fixed and `helperWrapper` adjusted in both components `Input` and `Select`, it also impacts the `Autocomplete`.
Multiline Select doesn't work as expected:
Multiline Select label styles fixed:

fix(select): multiline label

---

.changeset/quick-penguins-worry.md
packages/components/input/src/use-input.ts
packages/components/input/stories/input.stories.tsx
packages/components/select/stories/select.stories.tsx
packages/core/theme/src/components/input.ts
packages/core/theme/src/components/select.ts

Closes # 
- Select without label position fixed
- Input helperWrapper position is now relative to its parent

fix(select): without label and input helperWrapper relative

---

.changeset/gold-points-tap.md
apps/docs/content/docs/components/dropdown.mdx
apps/docs/content/docs/components/listbox.mdx
packages/components/listbox/src/base/listbox-section-base.tsx
packages/components/listbox/src/listbox-section.tsx
packages/components/menu/src/base/menu-section-base.tsx
packages/components/menu/src/menu-section.tsx

Closes #1888 
#1888 
`hideSelectedIcon` added to menu and listbox sections.

fix(menu): add hideSelectedIcon prop to menu and listbox sections

---

.changeset/witty-colts-invent.md
apps/docs/app/examples/perf/page.tsx
packages/core/system-rsc/src/extend-variants.js

Closes #1921 
The `extendVariants` function doesn't consider the props variants when having default ones defined.
The `extendVariants` function prioritizes the prop variants over the default ones

fix(system): extend variants fuction adapted

---

.changeset/happy-rice-walk.md
packages/components/input/src/textarea.tsx

chore(textarea): refactor Textarea component props and add hasHelper prop

---

.changeset/unlucky-bikes-care.md
packages/components/switch/src/switch.tsx
packages/components/switch/src/use-switch.ts
packages/components/switch/stories/switch.stories.tsx

Fixes the switch element, it should be an input instead of a label.

fix(switch): element type

---

.changeset/silent-lemons-mate.md
packages/components/tabs/src/use-tabs.ts

Closes #1938 
Selected key type fixed in `Tabs` component.

fix(tabs): selected key prop duplicated type removed

---

apps/docs/content/docs/components/tooltip.mdx

In version 2.2.x, the classNames prop for tooltips is not of type Record<"base"｜"arrow", string>, it should be of type Record<"base"｜"content", string>.

fix(docs): wrong tooltip classNames type

---

apps/docs/content/docs/components/autocomplete.mdx
apps/docs/content/docs/components/select.mdx

Closes #1989 
Fix `disableSelectionIconRotation` to `disableSelectorIconRotation`.
> Incorrect attribute referenced.
> Correct attribute referenced.
No

Fix Autocomplete & Select docs with correct reference to `disableSelectorIconRotation`

---

.changeset/metal-weeks-vanish.md
packages/components/input/src/use-input.ts
packages/components/select/src/use-select.ts

Closes #1979 
Input, Autocomplete and Select label placement adjusted
Input, Autocomplete and Select height are not proportional when not having a label.
Label placement set to "outside" if the label property is not passed.

fix(input): label placement outside when label is missing

---

.changeset/orange-waves-speak.md
packages/components/input/src/use-input.ts

Closes #1984 
Input clearable feature fixed.
Pressing the clear button doesn't clear the input value.
Pressing the clear button clears the input value.

fix(input): clearable feature

---

apps/docs/content/docs/components/accordion.mdx

> This pull request fixes the typo in the accordion API documentation. `WWhether --> Whether`.
> The current documentation for the accordion contains a typographical error. In the "API" section, the word `WWhether` is used instead of the correct spelling, which is `Whether`.
> Documentation without typo.
> Definitely no.

docs(accordion): fix typo

---

apps/docs/content/components/modal/custom-styles.ts

> This fix corrects the property type of the custom-styled modal. The radius `2xl`, which is not even listed in the API documentation for the modal, is replaced with `lg`.
> The behavior should be changed since `2xl` is not even implemented. I believe the modal in the example is displayed with a radius of `lg`.
> Modal code snipped fits to displayed modal in the example.
No

docs(modal): fix radius property

---

apps/docs/content/docs/components/radio-group.mdx

Closes #2334
The Radio component's URL link for Storybook was configured wrongly.
Updated that to the correct URL.
old: https://storybook.nextui.org/?path=/story/components-radio--default
new: https://storybook.nextui.org/?path=/story/components-radiogroup--default
The Storybook throws the error. (the pic below)
No error.
No.

docs(components): radioGroup component link for Storybook does not work

---

packages/components/tabs/stories/tabs.stories.tsx

Closes #2343
If you go to the Tabs component Storybook through the link in the documentation. The Storybook throws the error.
The Storybook throws the error. (the pic below)
No error.
old: https://storybook.nextui.org/?path=/story/components-tabs--static
new: https://storybook.nextui.org/?path=/story/components-tabs--default
Any other component has "--default" suffix for its URL uniformly. So I conformed this one to the standard.
No.

docs(components): tabs component link for storybook does not work

---

packages/components/table/stories/table.stories.tsx

Closes #2341
If you go to the Table component Storybook through the link in the documentation. The Storybook throws the error.(the pic below)
The Storybook throws the error. (the pic below)
No error. 
old: https://storybook.nextui.org/?path=/story/components-table--static
new: https://storybook.nextui.org/?path=/story/components-table--default
Any other component has "--default" suffix for its URL uniformly. So I conformed this one to the standard.
No.

docs(components): table component link for storybook does not work

---

.changeset/pretty-mice-suffer.md
packages/components/spinner/src/spinner.tsx

Fixes the issue with `classNames.label` not being passed to spinner's label slot
The `<span>` rendered when `label` is defined cannot be styled using `classNames.label`
The classes defined in `classNames.label` are passed down to the slot, which allows styling the element
No

fix(spinner): pass classNames.label to slot

---

.changeset/itchy-shirts-build.md
packages/components/input/src/use-input.ts

Closes #2255
Set Date, Time, Month, Week and Range as `isFilled` as well.
Currently the labels would overlap in Date, Time, Month, Week and Range. Screenshot retrieved from the original issue post.
No

fix(components): input label overlapping issue

---

apps/docs/content/docs/frameworks/astro.mdx

If you are trying to add NextUI to a brand new Astro project, you might forget to install React first.
As a result, this PR adds that step -- with a link to the Astro documentation, similar to the Tailwind advice.
The current documentation assumes the Astro project already has React installed, but a fresh Astro project will not.
This revised documentation is simply more explicit about integrating React in Astro before installing NextUI.
No.

Added note for installing React.

---

apps/docs/content/components/modal/non-dismissable.ts
apps/docs/content/docs/components/modal.mdx

Closes https://github.com/nextui-org/nextui/issues/2214
Corrected a mistake in the documentation regarding non-dismissable modals.
Behavior was not correct for the description.
The demo modal was being closed with the Esc key.
`isKeyboardDismissDisabled` props had to be set to true to prevent the modal from closing with the Esc key.
No.

docs(modal): update documentation to include dismiss properties

---

.changeset/mighty-ladybugs-joke.md
packages/core/theme/src/components/toggle.ts

Closes #2266
Added missing RTL styles in toggle
Switches with RTL never toggle
[pr2392-demo.webm](https://github.com/nextui-org/nextui/assets/35857179/245e647c-583a-4cc2-8e74-730684d9a8c8)
No

fix(components): rtl styles in toggle

---

.changeset/strange-onions-bow.md
packages/components/pagination/package.json
packages/components/pagination/src/pagination.tsx
packages/components/pagination/src/use-pagination.ts
packages/hooks/use-pagination/package.json
packages/hooks/use-pagination/src/index.ts
pnpm-lock.yaml

Closes #2292
- invert pagination arrow buttons and fix the logic
- the arrow buttons are inverted and the logic is not correct in RTL case
[pr2393-demo.webm](https://github.com/nextui-org/nextui/assets/35857179/0e0f1574-8475-4a44-b112-a1a79cbb32d2)
No

fix: pagination RTL

---

apps/docs/components/docs/components/swatch-colors-set.tsx
packages/core/theme/stories/colors.stories.tsx

fix: sematic typos

---

apps/docs/app/examples/navbar/controlled-menu/page.tsx
apps/docs/app/examples/navbar/disable-menu-animation/page.tsx

Closes #2225
- The layout and color in With Menu (disableAnimation) & Controlled Menu are not consistent with other examples.
No

fix(docs): keep navbar layout consistent

---

.changeset/fuzzy-panthers-hear.md
packages/hooks/use-data-scroll-overflow/src/index.ts

Closes #2010
change `topBottom` and `leftRight` to `top-bottom` and `left-right`
Using `data-top-bottom-scroll="true"` as an example. 
Before triggering `clearOverflow`, we can see `data-top-bottom-scroll` which is expected.
After triggering `clearOverflow`, `data-top-bottom-scroll` is still here, which is not expected.
Before triggering `clearOverflow`, we can see `data-top-bottom-scroll` which is expected.
After triggering `clearOverflow`, with the fix in this PR, `data-top-bottom-scroll="true"` is removed as expected.
No

fix(hooks): incorrect attribute names in clearOverflow

---

.changeset/five-panthers-dress.md
packages/components/modal/src/modal-transition.ts

Closes #2382 
Fixes typo in CSS variable access syntax
Console shows a warning and transition of modal doesn't complete as expected.
No more warnings, transition works as expected.
No

fix: #2382 typo in modal transition CSS variable access

---

.changeset/two-lobsters-sip.md
packages/components/dropdown/src/use-dropdown.ts

Closes #2276
[Based on the docs](https://nextui.org/docs/components/dropdown#dropdown-props), adding an isDisabled prop and setting it to true does not disable a dropdown
The `isDisabled` prop does not work, because the Dropdown component does not pass the `isDisabled` prop to the PopoverTrigger component.
It disables the trigger when `isDisabled` prop gets passed.
https://github.com/nextui-org/nextui/assets/62743644/268482fe-6a70-461f-8981-81d8cd3f559f
No.
N/A

fix(components): isdisabled does not disable dropdown

---

.changeset/rare-bears-cross.md
packages/core/theme/src/components/chip.ts

Closes # 
#2350 
fix(chip): add min width avoid chip malformed (#2350)
No

fix(chip): avoid chip malformed (#2350)

---

packages/components/chip/stories/chip.stories.tsx

> Added `ChipProps` import to resolve TypeScript error.
> `Cannot find name 'ChipProps'.ts(2304)` due to missing import.
> `ChipProps` imported alongside `Chip` component, resolving the error.
> No

fix: added missing ChipProps import

---

package.json

This PR updates the dev script in package.json to only execute pnpm sb.
Currently, the dev script is set to pnpm sb && pnpm dev:docs, which causes an issue where pnpm dev:docs does not execute because pnpm sb runs indefinitely.
With this update, running pnpm dev will only start the Storybook server.
No.

fix: update dev script to only run pnpm sb

---

apps/docs/app/docs/[[...slug]]/page.tsx

there was duplicate url // on the route caused from ```CONTENT_PATH ``` 
> 
>  I just fixed the // to have a / that comes from the ```CONTENT_PATH``` instead of adding a new one
<! It does not break any changes at all
there are a couple of ways to implement this kind of approach .. lemme know what you think

fix: dup // fix on a link for edit this page on github

---

apps/docs/content/components/autocomplete/controlled.ts

> This adds the missing `defaultItems` property to the Controlled Autocomplete for the typescript snippet.
> The example doens't work correctly when copy & pasted. --> Could mislead the user.
> The example works now.
No.

docs(autocomplete): fix missing defaultItems property

---

apps/docs/content/components/button/custom-impl.ts

Fixed a TypeScript onClear type error in the button component custom implementation sample code.
Closes #2211 
Depending on the response from the issue poster, we may make additional corrections, but in that case we will post a separate PR.
No.

docs(components): fixed Custom Implementation  sample for button component missing onClear type

---

.changeset/metal-gorillas-dress.md
packages/components/autocomplete/src/use-autocomplete.ts

Closes #2372
Autocomplete, tabIndex is not passed on input
`inputProps` don't get passed down to the input element.
It is used to `otherProps` override `slotsProps.inputProps`. Now `slotsProps.inputProps`(user input) takes precedence over.
No.

fix(components): autocomplete, tabIndex is not passed on input

---

.changeset/metal-peas-act.md
packages/utilities/react-rsc-utils/src/dom-props.ts

Closes #2432
- currently `enterKeyHint` in `otherProps` got filtered out since it is not considered as a dom prop.
- e.g. `<Input {...args} enterKeyHint="search" />`, `enterKeyHint` will be ignored.
It shows `return`, which is not expected.
It shows `search`, which is not expected.

fix(utils): include enterKeyHint in dom-props

---

package.json

replace `rm` with rimraf while deleting node_modules during `pnpm clean` to support in both Windows and Linux.
Closes #2442
Replace `rm -rf` with `rimraf` in `[pnpm clean](clean:node-modules)` in root package.json scripts.
`[pnpm clean](clean:node-modules)` script used for `node_modules` cleaning doesn't work in Windows OS as `rm` command is not internal.
Deletes root `node_modules` in Windows OS as well with `rimraf`.
No
NA

chore (pnpm clean) - `rimraf` Instead of `rm` for Windows OS Support

---

.changeset/thirty-bugs-beg.md
packages/components/autocomplete/src/use-autocomplete.ts
packages/components/autocomplete/stories/autocomplete.stories.tsx

Closes #2420
- revised the isReadOnly logic in Autocomplete
- created `isReadOnly` example in storybook
when `isReadOnly` is set, users 
- cannot edit the input
- can open the listbox
- can select the menu option
when `isReadOnly` is set, users 
- cannot edit the input
- can open the listbox
- cannot select the menu option
No
When someone prefer to not open the listbox, then they should use `isDisabled` instead.

fix: isReadOnly in Autocomplete

---

.changeset/spotty-pens-stare.md
packages/components/tooltip/src/tooltip.tsx

Closes #1840 
Add a condition to check if `children` is valid ReactElement.
When Tooltip gets string or number as children, they are not rendered.
Now they will show on the screen normally.

Fix(tooltip): allow non-ReactElement children

---

package.json

replaced `rm` with `rimraf` in `pnpm:lock` in root package.json to support windows
Closes #2453
Replace `rm` with rimraf in [pnpm clean](clean:lock) in root package.json script.
`[pnpm clean](clean:lock)` script used for `pnpm-lock.yaml` cleaning doesn't work in Windows OS as rm command is not internal.
Deletes root `pnpm-lock.yaml` in Windows OS as well with rimraf.
No
No

chore(pnpm:lock script): `rimraf` for windows support

---

.changeset/famous-owls-kick.md
packages/core/theme/src/components/table.ts

Closes #2471
Add RTL support to the table component.
The table component currently lacks support for right-to-left (RTL) direction.
This PR addresses the RTL support issue in the switch component, ensuring correct rendering in RTL environments.

fix: add RTL support to the Table component

---

packages/components/table/src/table-body.tsx

Closes #2470
This change ensures that `emptyContent` is hidden if `isLoading` is `true`
Currently, if `loadingContent` and `emptyContent` are both provided, and `isLoading` is true, NextUI will render both of them on top of each other.
This change suppresses the rendering of `emptyContent` if `isLoading` is true.
No.
Note that there's an existing issue with `loadingContent` where if `emptyContent` is **not** provided, NextUI will render `loadingContent` on top of the columns (instead of inside the table). This change doesn't fix that, but rather make `isLoading`/`loadingContent` play nice with a provided `emptyContent`. A separate fix is still needed for when `emptyContent` is not provided.

fix(table): hide empty content if isLoading is true (#2470)

---

apps/docs/content/components/image/blurred.ts

Closes #2539
`classNames` -> `className` since the type is `Record<"img"｜ "wrapper"｜ "zoomedWrapper"｜ "blurredImg", string>`, not `string`.
`classNames="m-5"`
`className="m-5"`
No

fix(docs): className in image blurred example

---

packages/components/date-input/__tests__/time-input.test.tsx
packages/components/date-input/src/index.ts
packages/components/date-input/src/time-input.tsx
packages/components/date-input/src/use-time-input.ts
packages/components/date-input/stories/time-input.stories.tsx
packages/components/date-picker/intl/messages.ts
packages/components/date-picker/src/date-picker.tsx
packages/components/date-picker/src/use-date-picker.ts
packages/components/date-picker/stories/date-picker.stories.tsx
packages/components/popover/src/free-solo-popover.tsx
packages/core/theme/src/components/date-picker.ts
packages/utilities/shared-icons/src/bold/clock-square-bold.tsx
packages/utilities/shared-icons/src/bold/index.ts
packages/utilities/shared-icons/src/linear/clock-circle-linear.tsx
packages/utilities/shared-icons/src/linear/index.ts

TimeInput Component 🕒

---

packages/core/theme/src/components/date-picker.ts

Closes #
**branch: v2.3.0**
In the DatePicker storybook, for the visibleMonth section, calendarContent(slot) does not widen enough its width.(demo video attached)
https://github.com/nextui-org/nextui/assets/62743644/803ef02f-79be-4076-8742-0a35a43c8f19
https://github.com/nextui-org/nextui/assets/62743644/db2a301d-e012-418c-a9da-397295ad0ccd
No

fix: Calendar visibleMonth UI glitch (to v2.3.0)

---

packages/components/calendar/src/calendar-picker.tsx
packages/components/calendar/src/use-calendar-picker.ts
packages/components/date-input/src/date-input-field.tsx
packages/components/date-input/src/date-input-group.tsx
packages/components/date-input/src/date-input.tsx
packages/components/date-input/src/index.ts
packages/components/date-input/src/time-input.tsx
packages/components/date-input/src/use-date-input.ts
packages/components/date-input/src/use-time-input.ts
packages/components/date-input/stories/date-input.stories.tsx
packages/components/date-picker/src/date-range-picker-field.tsx
packages/components/date-picker/src/date-range-picker.tsx
packages/components/date-picker/src/index.ts
packages/components/date-picker/src/use-date-picker-base.ts
packages/components/date-picker/src/use-date-picker.ts
packages/components/date-picker/src/use-date-range-picker.ts
packages/components/date-picker/stories/date-picker.stories.tsx
packages/components/date-picker/stories/date-range-picker.stories.tsx
packages/core/theme/src/components/date-input.ts
packages/core/theme/src/components/date-picker.ts

DateRangePicker Component 🗓️

---

.changeset/poor-years-help.md
packages/components/autocomplete/src/use-autocomplete.ts

- Closes: #1909
- Closes: #2460
Inside `useAutocomplete`, `useComboBox().inputProps.onKeyDown` causes following error message when user presses key:
>   stopPropagation is now the default behavior for events in React Spectrum. You can use continuePropagation() to revert this behavior.
Since `useComboBox` is imported from third-party dependency and has nothing to do with NextUI users, we can hide the error message by overwriting `inputProps.onKeyDown`.
When focus Autocomplete and press keys, error messages appear in the console.
Can't see such error messages anymore.

fix(use-autocomplete): overwrite `onKeyDown` to prevent meaningless error msg

---

.changeset/large-tips-pump.md
packages/core/theme/src/components/select.ts

Closes #2042
Add RTL support to the select component.
The select component currently lacks support for right-to-left (RTL) direction.
This PR addresses the RTL support issue in the select component, ensuring correct rendering in RTL environments.

fix(select): add RTL support to the select component (#2042)

---

.changeset/red-jobs-rest.md
packages/components/date-picker/src/date-range-picker-field.tsx

Closes # 
The DateRangePicker input is currenly always disabled/readonly 
The DateRangePicker input is currenly always disabled/readonly 
Static props removed from DateRange Field

fix(date-picker): invalid and disabled props removed

---

.changeset/clever-ties-glow.md
packages/components/modal/package.json
packages/components/modal/src/modal-content.tsx
packages/components/modal/src/use-modal.ts
packages/components/modal/stories/modal.stories.tsx
packages/hooks/use-aria-modal-overlay/src/index.ts
pnpm-lock.yaml

Closes #
`RemoveScrollWrapper` component was removed from `Modal` content since it was breaking the inside/outside scroll
Inside/Ourside scroll is not handled by the modal
`usePreventScroll` added to `useAriaModalOverlay` to handle the behind modal scroll instead of using the `react-remove-scroll` library

fix(modal): inside and outside scroll

---

apps/docs/content/components/date-input/start-end-content.ts

This PR request fixes the import issue in codesandbox for CalendarIcon instead of MailIcon
No

fix(docs): Date input start & end content calendar import issue (codesandbox)

---

.changeset/two-bananas-dance.md
packages/components/input/src/input.tsx

Closes #2069  
When `startContent` or `endContent` becomes truthy, it will change the position of `<input />` and React will re-mount `<input />`. This makes it losing focus. So we can remove the condition and just let `startContent` or `endContent` be in `innerWrapper` to make the position of `<input />` steady.
When `endContent` becomes truthy while user focusing input, input will lose focus.
Now input won't lose focus.

fix(input): keep input component's position in innerWrapper steady

---

.changeset/thirty-timers-press.md
packages/components/select/__tests__/select.test.tsx
packages/components/select/src/hidden-select.tsx

Closes #3156
as titled
currently, when we unselect an item, the value will be undefined which won't match any option in the hidden select. Therefore, the previous selected item was used. e.g: select `foo` -> unselect `foo` -> value: `'foo'`
if it is `undefined`, we use empty string instead, which keeps consistent with the one in `inputProps` as well (L96). e.g: select `foo` -> unselect `foo` -> value: `''`
No

fix(select): unset form value after unselecting an item

---

apps/docs/components/marketing/hero/floating-components.tsx

Closes # 
Previously NextUI Image component doesn't take height input, so it still looked ok when the height was incorrect.

fix(docs): incorrect image height in documentation

---

apps/docs/styles/globals.css

- Closes #3461
- Closes #2778 
`apps/docs/app/layout.tsx` 
The child element of the body have been added `position: relative`

fix(docs): remove body position which cause popover/tooltip wrong

---

.changeset/empty-countries-count.md
packages/core/theme/src/components/button.ts

Closes #3489
`data-[pressed=true]:scale-[0.97]` was moved from `disableAnimation` false case to global base in [here](https://github.com/nextui-org/nextui/pull/2929/files#diff-ae075221d59003e0b1c8add05fbb594132e2df8bd2d6b987f48aec5188166486L89). With such change, `data-[pressed=true]:scale-[0.97]` will be also applied to the true case now.
there is scaling on press when `disableAnimation` is `true`
[pr3499-before.webm](https://github.com/user-attachments/assets/31cac2d4-b047-4200-b6a4-22a731aa73b3)
there is no scaling on press when `disableAnimation` is `true`
[pr3499-after.webm](https://github.com/user-attachments/assets/11779b02-9380-424c-a9d6-9d493385d114)

fix(theme): button scaling when disableAnimation is true

---

.changeset/seven-apricots-happen.md
packages/components/modal/src/modal-content.tsx
packages/core/theme/src/components/modal.ts

- Closes: #2837
- Closes: #2838
- Closes: #3241
If there is input in modal where the position is bottom, when the keyboard is open, it covers the input which results in bad UX.
No

fix(modal): modal position when keyboard appears

---

.changeset/eleven-eels-fix.md
packages/core/theme/src/components/button.ts
packages/core/theme/src/utils/variants.ts

Closes #2095 
`colorVariants.ghost` uses pseudo-class hover
When touch ghost button on mobile, it will show hovering style and keep it until you touch elsewhere.
Now ghost button won't show hovering style on mobile.
I removed hover style from `colorVariants.ghost` since currently it's used only in `Button` theme.

fix(theme): use data-hover instead of hover

---

.changeset/silent-ads-mix.md
apps/docs/app/examples/perf/page.tsx
apps/docs/components/theme-switch.tsx
apps/docs/content/components/input/custom-styles.ts
apps/docs/content/components/select/custom-styles.ts
apps/docs/content/components/switch/custom-styles.ts
apps/docs/content/customization/custom-variants/slots-component.ts
apps/docs/content/docs/customization/custom-variants.mdx
packages/components/select/stories/select.stories.tsx
packages/core/theme/src/components/autocomplete.ts
packages/core/theme/src/components/checkbox.ts
packages/core/theme/src/components/date-input.ts
packages/core/theme/src/components/date-picker.ts
packages/core/theme/src/components/input.ts
packages/core/theme/src/components/radio.ts
packages/core/theme/src/components/select.ts
packages/core/theme/src/components/toggle.ts

Closes # 
The changes included in those PR would require users to update their customised styles. Hence, reschedule them to 2.5.0.

chore: undo pr3658 & pr3751

---

.changeset/gentle-needles-rescue.md
packages/hooks/use-image/__tests__/use-image.test.tsx
packages/hooks/use-image/src/index.ts

fix: image load on next.js

---

.changeset/ten-paws-relate.md
packages/components/popover/src/popover-trigger.tsx

fix: element.ref was removed in React 19 warning

---

apps/docs/content/components/tooltip/arrow.raw.jsx
apps/docs/content/components/tooltip/arrow.ts
apps/docs/content/components/tooltip/colors.raw.jsx
apps/docs/content/components/tooltip/colors.ts
apps/docs/content/components/tooltip/controlled.raw.jsx
apps/docs/content/components/tooltip/controlled.ts
apps/docs/content/components/tooltip/custom-content.raw.jsx
apps/docs/content/components/tooltip/custom-content.ts
apps/docs/content/components/tooltip/custom-motion.raw.jsx
apps/docs/content/components/tooltip/custom-motion.ts
apps/docs/content/components/tooltip/custom-styles.raw.jsx
apps/docs/content/components/tooltip/custom-styles.ts
apps/docs/content/components/tooltip/delay-multiple.raw.jsx
apps/docs/content/components/tooltip/delay-multiple.ts
apps/docs/content/components/tooltip/delay.raw.jsx
apps/docs/content/components/tooltip/delay.ts
apps/docs/content/components/tooltip/offset.raw.jsx
apps/docs/content/components/tooltip/offset.ts
apps/docs/content/components/tooltip/placements.raw.jsx
apps/docs/content/components/tooltip/placements.ts
apps/docs/content/components/tooltip/usage.raw.jsx
apps/docs/content/components/tooltip/usage.ts

refactor(docs): tooltip dx

---

apps/docs/content/components/circular-progress/colors.raw.jsx
apps/docs/content/components/circular-progress/colors.ts
apps/docs/content/components/circular-progress/custom-styles.raw.jsx
apps/docs/content/components/circular-progress/custom-styles.ts
apps/docs/content/components/circular-progress/label.raw.jsx
apps/docs/content/components/circular-progress/label.ts
apps/docs/content/components/circular-progress/sizes.raw.jsx
apps/docs/content/components/circular-progress/sizes.ts
apps/docs/content/components/circular-progress/usage.raw.jsx
apps/docs/content/components/circular-progress/usage.ts
apps/docs/content/components/circular-progress/value-formatting.raw.jsx
apps/docs/content/components/circular-progress/value-formatting.ts
apps/docs/content/components/circular-progress/value.raw.jsx
apps/docs/content/components/circular-progress/value.ts

refactor(docs): circular-progress dx

---

apps/docs/content/components/code/colors.raw.jsx
apps/docs/content/components/code/colors.ts
apps/docs/content/components/code/sizes.raw.jsx
apps/docs/content/components/code/sizes.ts
apps/docs/content/components/code/usage.raw.jsx
apps/docs/content/components/code/usage.ts

refactor(docs): code dx

---

apps/docs/content/components/progress/colors.raw.jsx
apps/docs/content/components/progress/colors.ts
apps/docs/content/components/progress/custom-styles.raw.jsx
apps/docs/content/components/progress/custom-styles.ts
apps/docs/content/components/progress/indeterminate.raw.jsx
apps/docs/content/components/progress/indeterminate.ts
apps/docs/content/components/progress/label.raw.jsx
apps/docs/content/components/progress/label.ts
apps/docs/content/components/progress/sizes.raw.jsx
apps/docs/content/components/progress/sizes.ts
apps/docs/content/components/progress/striped.raw.jsx
apps/docs/content/components/progress/striped.ts
apps/docs/content/components/progress/usage.raw.jsx
apps/docs/content/components/progress/usage.ts
apps/docs/content/components/progress/value-formatting.raw.jsx
apps/docs/content/components/progress/value-formatting.ts
apps/docs/content/components/progress/value.raw.jsx
apps/docs/content/components/progress/value.ts

refactor(docs): progress dx

---

apps/docs/content/components/textarea/autosize.raw.jsx
apps/docs/content/components/textarea/autosize.ts
apps/docs/content/components/textarea/controlled.raw.jsx
apps/docs/content/components/textarea/controlled.ts
apps/docs/content/components/textarea/description.raw.jsx
apps/docs/content/components/textarea/description.ts
apps/docs/content/components/textarea/disable-autosize.raw.jsx
apps/docs/content/components/textarea/disable-autosize.ts
apps/docs/content/components/textarea/disabled.raw.jsx
apps/docs/content/components/textarea/disabled.ts
apps/docs/content/components/textarea/error-message.raw.jsx
apps/docs/content/components/textarea/error-message.ts
apps/docs/content/components/textarea/readonly.raw.jsx
apps/docs/content/components/textarea/readonly.ts
apps/docs/content/components/textarea/required.raw.jsx
apps/docs/content/components/textarea/required.ts
apps/docs/content/components/textarea/usage.raw.jsx
apps/docs/content/components/textarea/usage.ts
apps/docs/content/components/textarea/variants.raw.jsx
apps/docs/content/components/textarea/variants.ts

refactor(docs): textarea dx

---

apps/docs/content/docs/components/date-input.mdx
apps/docs/content/docs/components/date-picker.mdx
apps/docs/content/docs/components/date-range-picker.mdx
apps/docs/package.json
pnpm-lock.yaml

Closes # 
For date related components, users may need to install `@internationalized/date` and `@react-aria/i18n`, in the existing documentation, the commands would lead them to install the latest one. However, the installed versions may not be same as the ones using in the packages. Hence, the discrepancy causes some unexpected behaviour. 
This PR simply add the current package version in the commands to ensure the versions are consistent.
related:
- https://github.com/nextui-org/nextui/issues/3604
- https://github.com/nextui-org/nextui/issues/4137
- https://github.com/nextui-org/nextui/issues/3963

refactor(docs): specify versions for date packages

---

apps/docs/content/components/popover/arrow.raw.jsx
apps/docs/content/components/popover/arrow.ts
apps/docs/content/components/popover/backdrop.raw.jsx
apps/docs/content/components/popover/backdrop.ts
apps/docs/content/components/popover/colors.raw.jsx
apps/docs/content/components/popover/colors.ts
apps/docs/content/components/popover/controlled.raw.jsx
apps/docs/content/components/popover/controlled.ts
apps/docs/content/components/popover/custom-motion.raw.jsx
apps/docs/content/components/popover/custom-motion.ts
apps/docs/content/components/popover/custom-styles.raw.jsx
apps/docs/content/components/popover/custom-styles.ts
apps/docs/content/components/popover/custom-trigger.raw.jsx
apps/docs/content/components/popover/custom-trigger.ts
apps/docs/content/components/popover/offset.raw.jsx
apps/docs/content/components/popover/offset.ts
apps/docs/content/components/popover/placements.raw.jsx
apps/docs/content/components/popover/placements.ts
apps/docs/content/components/popover/title-props.raw.jsx
apps/docs/content/components/popover/title-props.ts
apps/docs/content/components/popover/usage.raw.jsx
apps/docs/content/components/popover/usage.ts
apps/docs/content/components/popover/variants.raw.jsx
apps/docs/content/components/popover/variants.ts
apps/docs/content/components/popover/with-form.raw.jsx
apps/docs/content/components/popover/with-form.ts

refactor(docs): popover dx

---

.changeset/calm-weeks-tie.md
packages/components/accordion/package.json
packages/components/button/package.json
packages/components/card/package.json
packages/components/date-picker/package.json
packages/components/navbar/package.json
packages/components/snippet/package.json
pnpm-lock.yaml

Closes # 
The previous PR https://github.com/nextui-org/nextui/pull/4140 resolves the calendar framer-motion error caused in user's react 19 + nextsj 15 repo. Hence, this PR is to cover all components.

fix(deps): missing peer / dev dependency for framer-motion

---

.changeset/happy-guests-warn.md
packages/components/checkbox/src/use-checkbox.ts
packages/components/radio/src/use-radio.ts
packages/components/switch/src/use-switch.ts

fix(touch): fixing the selection functionality on touch

---

.changeset/eighty-buttons-do.md
packages/components/form/__tests__/form.test.tsx
packages/components/form/src/form.tsx

fix: ref in form component

---

.changeset/chatty-pants-tickle.md
apps/docs/content/docs/components/checkbox.mdx

fix: build

---

apps/docs/app/docs/[[...slug]]/page.tsx
apps/docs/app/providers.tsx
apps/docs/components/navbar.tsx
apps/docs/package.json
apps/docs/styles/globals.css
pnpm-lock.yaml

fix: documentation re-renders

---

.changeset/polite-dingos-call.md
packages/components/alert/src/use-alert.ts

fix(alert): slots & variantProps import

---

.changeset/chilled-files-serve.md
packages/components/calendar/src/calendar-base.tsx

- Closes #4358 
- Closes #4068 
In 2.3.0, `PopLayoutWrapper` was used to forward the ref. 
```tsx
const PopLayoutWrapper = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
(props, ref) => {
return <div ref={ref} {...props} />;
},
);
```
At some point (couldn't trace when probably due to force push), it was changed to use React.Fragment, i.e. `<></>`. This is where the error is thrown.
In Ripple component, there is the same pattern (i.e. replace `PopLayoutWrapper` by `<></>`) and the fragment got removed in [this commit](https://github.com/nextui-org/nextui/commit/422770cc6bcdd1d4c51257654ab718f3c19d6cb2#diff-1406de614abf1c88f70eb8d86d1046e16a85a8d5ba3b057405d571097ca1f468). Hence, applying the same change to `calendar-base.tsx`.
Sandbox provided by the user: …

fix(calendar): invalid prop ref supplied to React.Fragment

---

.changeset/neat-badgers-beam.md
.changeset/new-cups-tan.md
packages/components/alert/src/use-alert.ts
packages/core/theme/src/components/alert.ts

Closes #4445 
`description` is marked as required (from the earliest design). At some point (around 2 months ago), `description` is only shown when it is provided based on [alert.tsx#L66](https://github.com/nextui-org/nextui/blob/canary/packages/components/alert/src/alert.tsx#L66). Hence, it indicates that it should be optional.
Also, when no title & description are provided, says `<Alert>Hello</Alert>`, the children position is a bit off. This PR also fixes the styling to make it look more natural (see the screenshots below).

fix(alert): mark description optional & revise styles when only children is provided

---

.changeset/honest-waves-camp.md
packages/components/navbar/src/navbar-menu.tsx

Closes eng-1823
- Overlay is used to provide a focus scope for child components
- this is useful for things like modals and popovers
- should only be applied to the page when the child with focus scope is open
- NavbarMenu applies Overlay to page even though its closed
- this causes other Overlay components like Select and Autocomplete to behave as if they are in a modal
- this PR makes it so Overlay is only applied by NavbarMenu when it is open
Note that it takes 2 clicks: one to close current Select and one to open a different Select
https://github.com/user-attachments/assets/bbaf057d-ffce-4076-bf1b-5e654b798fbb
1 click to close current Select and open a different Select
https://github.com/user-attachments/assets/1d58c904-73a3-47fa-91c7-f60c880802f9
No

fix(navbar): hide overlay when menu is closed

---

packages/components/input/__tests__/input.test.tsx
packages/components/input/src/use-input.ts

Reverts frontio-ai/heroui#4483

Revert "fix(input): use onPress for wrapper click focus"

---

.changeset/stale-bears-wink.md
packages/core/theme/src/components/modal.ts
packages/core/theme/src/components/popover.ts

Closes #4586
As title, following the doc.

fix(theme): add missing shadow none

---

apps/docs/tailwind.config.js

Closes # 
Fixed the configuration issue of the `bg-grid` plugin in `tailwind.config.js` by adding the missing `values` configuration, ensuring the plugin can correctly generate grid background styles based on background colors.
In the `<mcfile name="tailwind.config.js" path="f:\Code\fontEndHub\heroui\apps\docs\tailwind.config.js"></mcfile>` file, the `bg-grid` plugin was missing the `values` configuration when using `matchUtilities`, causing the plugin to fail to correctly retrieve background color values and generate corresponding CSS classes.
Added `values: flattenColorPalette(theme("backgroundColor"))` configuration to ensure the `bg-grid` plugin can correctly generate grid background styles based on background colors.
No
After the fix, you can verify it with:
```html
<div …
```

fix(tailwind): add missing values config for bg-grid plugin

---

apps/docs/components/marketing/custom-themes/styles.ts

Closes #
This PR fixes the issue with the incorrect display of rounded corner shadows on the official website. The shadow was not being rendered correctly in certain browsers, and this update addresses that problem.
The rounded corner shadows on the website are displayed incorrectly in some browsers. This visual issue impacts the overall design and user experience.
After this fix, the rounded corner shadows are displayed correctly across all supported browsers. The visual appearance of the website is now consistent with the intended design.
No
This fix primarily affects the visual rendering of the rounded corner shadows on the website. No major changes to functionality or behavior were introduced.

fix: rounded corner shadow bug

---

apps/docs/app/docs/[[...slug]]/page.tsx
apps/docs/components/mdx-content.tsx
apps/docs/hooks/use-mdx-component.ts
apps/docs/package.json

fix(docs): mdx in beta

---

.changeset/sharp-gifts-invite.md
packages/components/avatar/src/use-avatar.ts
packages/components/image/src/use-image.ts
packages/hooks/use-image/src/index.ts

Closes #3847
- `use-image` will load the image. If users use custom component, it will load twice. 
- This PR is to check if custom component is in use, then bypass the internal load
- Also fixes `disableAnimation` passing to Avatar if using non HeroUI component

fix: double fetch img src

---

.changeset/nine-carrots-pay.md
apps/docs/content/docs/components/table.mdx
packages/components/table/src/virtualized-table.tsx

Closes #4995
Currently if users use `removeWrapper` on a virtualized table, the table content won't be shown since the height is not determined. In this case, the wrapper is required. This PR is to remove the `removeWrapper` rendering logic for virtualized table and update the docs.

fix(table): remove removeWrapper on virtualized table

---

apps/docs/content/docs/design-principles.mdx

Closes # 
Update component example to use ref prop instead of `forwardRef`
N/A
N/A
No

docs: update component example to use ref prop instead of forward-ref
